### ISSUE TITLE
INVALID_TRACK is not defined in ImageCaptureError.

### ISSUE THREAD

**Issue by munrochiang** [w3c/mediacapture-image#10]
The spec mention " a new ImageCaptureError object whose errorDescription is set to INVALID_TRACK".

But  INVALID_TRACK is not defined in ImageCaptureError.

"The errorDescription attribute returns the appropriate DOMString for the error event. Acceptable values are FRAME_ERROR, OPTIONS_ERROR, PHOTO_ERROR, and ERROR_UNKNOWN."

The same problem has been reported here. http://lists.w3.org/Archives/Public/public-media-capture/2014Aug/0065.html

**Comment by gmandyam** [comment]
PR from https://github.com/w3c/mediacapture-image/pull/12 addresses this issue.
