### ISSUE TITLE
Nicer PR merging / cleaner GitHub history

### ISSUE THREAD

**Issue by dandv** [w3c/mediacapture-image#101]
https://github.com/w3c/mediacapture-image/commits/gh-pages

vs. 

![image](https://cloud.githubusercontent.com/assets/33569/18777400/c7fb83f4-8123-11e6-8590-829df0a8d101.png)

Result:

![image](https://cloud.githubusercontent.com/assets/33569/18777421/eda7964c-8123-11e6-89da-2f4c2b516ded.png)

Details: http://stackoverflow.com/questions/27208042/neat-clean-compacted-git-pr-and-merge-commit-into-one-commit/29958324#29958324

**Comment by miguelao** [comment]
I'm using squash-and-merge these last days and it's much better, thanks @dandv . Is there any more actionable items out of this issue...?

**Comment by dandv** [comment]
Looks great now, thanks!
