### ISSUE TITLE
Replace redEye example with one exercising zoom.

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#103]
Replace example num.2 https://w3c.github.io/mediacapture-image/#taking-a-picture-with-red-eye-reduction-supported-and-used with an example manipulating e.g. Zoom, that is more visual and is already available, while the changes in #73 are being addressed. Will do that quickly.

**Comment by beaufortfrancois** [comment]
Hey @miguelao, I've just pushed a zoom example. WDYT?

**Comment by miguelao** [comment]
I like it!
