### ISSUE TITLE
mediaSettingsRange should return default value

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#104]
It should be very easy for developers to reset default value of `mediaSettingsRange` such as `brightness`, `contrast`, `saturation`, `sharpness`, and `zoom`.
Please provide this information when available.

``` diff
        interface MediaSettingsRange {
            readonly attribute long max;
            readonly attribute long min;
            readonly attribute long current;
+            readonly attribute long default;
        };
```

For info, I can get it with a Logitech C920:

``` sh
$ v4l2-ctl --dev=/dev/video1 -L        
                     brightness (int)    : min=0 max=255 step=1 default=128 value=128
                       contrast (int)    : min=0 max=255 step=1 default=32 value=32
                     saturation (int)    : min=0 max=255 step=1 default=32 value=32
 white_balance_temperature_auto (bool)   : default=1 value=1
                           gain (int)    : min=0 max=255 step=1 default=64 value=59
           power_line_frequency (menu)   : min=0 max=2 default=2 value=1
                                0: Disabled
                                1: 50 Hz
                                2: 60 Hz
      white_balance_temperature (int)    : min=2800 max=6500 step=1 default=4000 value=4428 flags=inactive
                      sharpness (int)    : min=0 max=255 step=1 default=72 value=72
         backlight_compensation (int)    : min=0 max=1 step=1 default=0 value=0
                  exposure_auto (menu)   : min=0 max=3 default=3 value=3
                                1: Manual Mode
                                3: Aperture Priority Mode
              exposure_absolute (int)    : min=3 max=2047 step=1 default=166 value=200 flags=inactive
         exposure_auto_priority (bool)   : default=0 value=1
                   pan_absolute (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                  tilt_absolute (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                 focus_absolute (int)    : min=0 max=255 step=17 default=68 value=85 flags=inactive
                     focus_auto (bool)   : default=1 value=1
                  zoom_absolute (int)    : min=1 max=5 step=1 default=1 value=5
```

**Comment by beaufortfrancois** [comment]
The only way for now is to unplug device ;(

**Comment by beaufortfrancois** [comment]
gentle ping @miguelao

**Comment by miguelao** [comment]
Hmm the UVC interface has indeed a default value, but Android and iOS APIs do not, so I would argue that this knowledge is not widespread enough to merit being in the spec.

**Comment by beaufortfrancois** [comment]
That raises an interesting point then.
We should definitely reset WebCam image settings when image Capture is destroyed. See bug I've filed at https://bugs.chromium.org/p/chromium/issues/detail?id=655094 2 weeks ago.

**Comment by miguelao** [comment]
@beaufortfrancois I have two concerns with your proposal:
- Javascript does not have the capacity to delete an object, just to mark it as deleted so that it can be garbaged collected at a point in the future.  This seems to point to the alternative solution of having JS collecting a first set of `PhotoCapabilities` right after construction, and restoring them whenever the WebApp deems appropriate.
- Say we have two `ImageCapturer`s, and one is deleted and, just for argumentation's sake, immediately destroyed, restoring default values. The other `ImageCapturer` would essentially have  the photo settings changed beyond its control. Is this an acceptable/desirable situation?

**Comment by beaufortfrancois** [comment]
> - Javascript does not have the capacity to delete an object, just to mark it as deleted so that it can be garbaged collected at a point in the future. This seems to point to the alternative solution of having JS collecting a first set of PhotoCapabilities right after construction, and restoring them whenever the WebApp deems appropriate.

Yup

> - Say we have two ImageCapturers, and one is deleted and, just for argumentation's sake, immediately destroyed, restoring default values. The other ImageCapturer would essentially have the photo settings changed beyond its control. Is this an acceptable/desirable situation?

Nope.
I would reset photo settings only when last Chrome ImageCapturer is garbage collected.

**Comment by miguelao** [comment]
@dandv in light of the previous discussion, do you think we {c,sh}ould add the capability of resetting the `ImageCapturer` object to its original values when being "destroyed" ?

Aside from that, @beaufortfrancois , are there any more actions associated with this issue?

**Comment by beaufortfrancois** [comment]
I may not be clear but here's what is currently happening on my Chromebook:

1. I play with a web app that lets me update my camera settings (saturation, brightness, zoom, etc.)
2. I close this app
3. I lose internet connection / I don't remember website / Web app is down (pick your favorite)
4. I can't change back my camera settings!
5. Restarting my Chromebook doesn't even work... I'm stuck with these settings ;(

**Comment by miguelao** [comment]
Re. https://github.com/w3c/mediacapture-image/issues/104#issuecomment-256912439, that looks more like an implementation problem 😋  -- VideoCaptureDeviceLinux in Chrome should restore the Capabilities when being destroyed (IOW I bet that the Chromium Android implementation would work as expected in your case). I filed https://crbug.com/662616 to track it.

**Comment by beaufortfrancois** [comment]
Thank you!
It looks like bug I've filed a month ago at https://bugs.chromium.org/p/chromium/issues/detail?id=655094
