### ISSUE TITLE
Create implementation status page

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#107]
It would be great to have a living document that shows the implementation status of the API on the different browsers / platforms like the Web Bluetooth API at https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md#chrome.

Something like:

Feature/Platform          | Chrome OS | Android | Mac | Linux | Windows |
------------------------- | :-------: | :-----: | :-: | :---: | :-----: |
getPhotoCapabilities()         |  ✓         | ✓        |     |       |         |
└ zoom         |  ✓         | ✓        |     |       |         |
└ brightness         |  55         | ✓        |     |       |         |
takePhoto()         |  ✓         | ✓        |     |       |         |
...

**Comment by miguelao** [comment]
Oh, nice! +1, I'll knock it off.

**Comment by miguelao** [comment]
@beaufortfrancois PTAL and let me know, preventively closing this Issue.

**Comment by beaufortfrancois** [comment]
See nits at https://github.com/w3c/mediacapture-image/pull/110
