### ISSUE TITLE
No need to define custom events in ImageCapture spec

### ISSUE THREAD

**Issue by munrochiang** [w3c/mediacapture-image#11]
I am almost finishing supporting promise-based TakePhoto on Gecko.
There is no need to define the custom events anymore.

**Comment by munrochiang** [comment]
In that case, we will get Blob instead of BlobEvent.

 function showPicture(e) {
     var img = document.querySelector("img");
-    img.src = URL.createObjectURL(e.data);
+    img.src = URL.createObjectURL(e);
     }

**Comment by gmandyam** [comment]
PR from https://github.com/w3c/mediacapture-image/pull/12 addresses this issue.
