### ISSUE TITLE
Separate getPhotoCapabilities from getSettings

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-image#123]
The mixture of getPhotoCapabilities and getting settings is painful for the platform users.
getPhotoCapabilities is likely done only once at object init time, while getSettings is probably done every time some operation needs to display or modify them.

This structure also prevents the easy use of setOptions as in getSettings().then(s=>{modify s; setOptions(s)).

**Comment by miguelao** [comment]
After introduction of the Constrainable Pattern, `getPhotoCapabilities()` returns [`PhotoCapabilities`](https://w3c.github.io/mediacapture-image/##photocapabilities-section) which contains no "current status", and [`MediaTrackCapabilities`](https://w3c.github.io/mediacapture-image/#mediatrackcapabilities-section) is also separated from [`MediaTrackSettings`](https://w3c.github.io/mediacapture-image/#mediatracksettings-section).  So I think this concern is addressed ==> closing.
