### ISSUE TITLE
Point2D does not specify relation to image frame

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-image#125]
If Point2D is a point in an unit square, with the upper left corner being the upper left corner of the image, the specification needs to specify where the other corners are. Either the top right corner should align (square contains image for horizontal aspect ratio, square is a subset of the image for vertical aspect ratio) or the bottom left corner should align (opposite effect).

Finding the center of the picture requires looking at width & height in all cases.

**Comment by alvestrand** [comment]
An alternate reading is that the coordinate space is not square, and (0.5, 0.5) is always the center. This is unusual enough that it should be explicit.

**Comment by miguelao** [comment]
> Either the top right corner should align (square contains image for horizontal aspect ratio, square is a subset of the image for vertical aspect ratio) or the bottom left corner should align (opposite effect).

What I wanted to convey was that `(1.0, 1.0)` would be the lower rightmost corner of the image. Essentially normalizing every coordinate `x`,`y` by `width`,`height`, respectively. WDYT? If it makes sense I'll add to the wording.

**Comment by miguelao** [comment]
@alvestrand : I wrote and merged some changes but I'm not closing this bug yet, please have a look and comment/close.

**Comment by miguelao** [comment]
ping @alvestrand

**Comment by miguelao** [comment]
Closing this issue preventively, reopen/comment if it's still relevant, thanks!
