### ISSUE TITLE
ISO setting is not well defined

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-image#127]
The definition of "ISO" says "This setting in most implementations relates to shutter speed, and is sometimes known as the ASA setting."

If it's related, it needs to say how it's related. But I don't think it is, not directly.

ISO needs to be referenced to the ISO standard that defines it (for color negative film: ISO 5800:2001, arithmetic scale - for digital cameras: ISO 12232:2006, which apparently gives choices for how to compute).

https://en.wikipedia.org/wiki/Film_speed#Digital_camera_ISO_speed_and_exposure_index gives some introduction.

**Comment by miguelao** [comment]
Digital cameras in general and Android in particular follows ISO12232, so adding the citation.  Note that the quoted text is in a non-normative section intended to clarify otherwise known facts.

**Comment by miguelao** [comment]
Closing as per my previous comments. As usual, please comment if this is still relevant, thanks!
