### ISSUE TITLE
"Implementation dependent" settings can't be made interoperable

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-image#128]
At the moment, brightness, contrast, saturation and sharpness are specified as "implementation dependent". As such, it is impossible to achieve an interoperable implementation based on the spec.

At least a zero-point, sign and magnitude of the measure should be defined - such as "zero sharpness refers to the camera's default setting; positive values mean edges are sharpened compared to the default settings, negative values mean that they are softened. Typical ranges are +1 to -1, but the supported range must be found using getPhotoCapabilities. If no sharpness control is implemented, the range is 0..0."

(this is NOT a concrete proposal, but an example of something that could make some claims of being independently implementable.)

**Comment by miguelao** [comment]
That's what the "Universal Serial Bus Device Class Definition for Video Devices Revision 1.5 August 9, 2012" gives us in e.g. its Section 4.2.2.3.2 Brightness Control: 
> This is used to specify the brightness. This is a relative value where increasing values indicate increasing brightness. The MIN and MAX values are sufficient to imply the resolution, so the RES value must always be 1. The MIN, MAX and default values are implementation dependent. This control must accept the GET_DEF request and return its default value.

Those four controls are just pass-through to UVC controls, so I don't see how this Spec can impose restrictions on them. FTR I've always seen those controls as a 0-255 scale, 128 being the middle value (i.e. it behaves as a signed char).  I'll add a comment with this info and link to the UVC standard. 

On the plus side, controls provide `max`,`min`, and `default` values, which would answer part of your question --  but now e.g. what would negative values do.

I wonder how other hardware-dependent Specs would tackle this problem.

**Comment by miguelao** [comment]
#136 clarified those fields and added a reference, please have a reading and reopen/comment here if appropriate, thanks!
