### ISSUE TITLE
MediaSettingsRange "step" should be optional

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-image#129]
(This does not apply if constraints are adopted)

For several of the parameters given, "step" doesn't give meaning. Either because they are continuous (f.ex. zoom), or because their steps are not the same size (f.ex. ISO).

In these cases, any value of "step" is meaningless, and it should be omitted.

**Comment by miguelao** [comment]
`step` as defined in `MediaSettingsRange` doesn't have any particular meaning except: 
> The minimum difference between consecutive values of this setting.

To my knowledge, all USB cameras comply with UVC, which uses natural numbers to send information, making the `step` value ` an integer (usually 1). 

Beyond that, in mobile platforms (see e.g. [Android CameraCharacteristics]( https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics.html)), we too have integers, including for `ISO`, that has a granularity of 1 ([SENSOR_SENSITIVITY](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#SENSOR_SENSITIVITY)), although in some other cases, e.g. [exposure compensation](https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics.html#CONTROL_AE_COMPENSATION_STEP), the number is nuanced and that's the reason why we must have the `step`.

Finally, `zoom` might be a continuous setting in digital cameras, but in mobile platforms it is almost always implemented by cropping a larger canvas and in that case the granularity is determined by the pixel size, and it might be supplied to the user.

My point being that every single setting has a regular step and it isn't straightforward to know it, hence the parameters is always need and non trivial.

**Comment by miguelao** [comment]
Closing per my comments before. Please reopen if this needs further discussion. Thanks!
