### ISSUE TITLE
Attribute PhotoCapabilities should not be a Dictionary

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#13]
in [this definition](http://w3c.github.io/mediacapture-image/index.html#image-capture-api), and because of [1]:
> Dictionaries must not be used as the type of an attribute or constant.

but it can be used as a return value of a getter instead?

[1] https://heycam.github.io/webidl/#idl-dictionaries

**Comment by gmandyam** [comment]
Do not understand this issue.  PhotoCapabilities is an interface:  http://w3c.github.io/mediacapture-image/#idl-def-PhotoCapabilities.  Is there misleading text in the spec?

**Comment by miguelao** [comment]
You're right @gmandyam I mistook ```PhotoCapabilities``` and ```PhotoSettings```. Closing this issue.
