### ISSUE TITLE
How to resolve conflicts with MediaStreamtrack.constraints needs to be specified

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-image#130]
If photo settings directly conflict with those of a MediaStreamTrack (such as "width" and "height"), or may cause the track to go out of its settings if applied (such as "iso" and "exposure", which may affect frame rate), the way to resolve the issue must be specified.

This may be specified as "the track is stopped, the source is reconfigured, the image is taken, the track is started", as specified as an example under the "takePhoto" option; this needs to be explicit.

The "grabFrame" method doesn't seem to have any such option; it should then be clear that it will ignore the photo options that are not possible to satisfy on the current track (if that's the intended reading).

**Comment by miguelao** [comment]
In the spirit of the other issues, I merged the new literature, please have a reading. Thanks!
