### ISSUE TITLE
Convert mediacapture-image to Bikeshed

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#139]
I very much like the [bikeshed](https://tabatkins.github.io/bikeshed/) conciseness, simplicity and the way we can link easily to other Specs (in particular to Media Capture and Streams), so I made a branch in my fork of this repo and created a parallel index2.bs (and index2.html), using bikeshed, and duplicating what we have now.  Results can be found [here](http://rawgit.com/Miguelao/mediacapture-image/pr_9_bikeshed/index2.html).

I propose changing this Spec to bikeshed. @gmandyam , @alvestrand, @stefhak , WDYT??

Only thing preventing this is that there is no group "webrtc", so I'm using DAP (Device APIs), which is only one half of this Spec. @dontcallmedom , can we do something about it?

**Comment by miguelao** [comment]
Forgot to say, I'm glad to help extending/adding the appropriate bikeshed/include/webrtc folder, just let me know and @dontcallmedom and I can figure it out.
+@tabatkins fyi

**Comment by gmandyam** [comment]
@miguelao 

I am OK with moving to bikeshed.  We use it in webauthn as well.

**Comment by alvestrand** [comment]
I'm in favor of letting editors do what editors find best.
Doing something that's common to multiple groups helps getting more people to submit patches, so I don't like obscure formats (like Word :-) ), but Bikeshed seems to be fairly popular, so this is not an issue for me.

**Comment by dontcallmedom** [comment]
@miguelao indeed, this would need adding the right boilerplate to bikeshed - in this case, I think it would have to be a "Media Capture Task Force" boilerplate, since we need to link to both groups, the right mailing list, etc.

**Comment by dontcallmedom** [comment]
@miguelao whenever you produce a pull request for the conversion, note that our current Travis configuration will be incompatible with it, so you'll probably want to nuke the .travis.yml file in it.

Also, using bikeshed means that publications to https://www.w3.org/TR/image-capture/ will no longer be done automatically from github - you'll have to trigger it manually when generating updates. But we can figure that out when we get there.

**Comment by miguelao** [comment]
@dontcallmedom, thanks for pointing those things out.  I guess we can do like in https://github.com/WICG/media-capabilities and have a [deploy.sh](https://github.com/WICG/media-capabilities/blob/master/deploy.sh) running a [Makefile](https://github.com/WICG/media-capabilities/blob/master/Makefile), would you know the exact mechanics?

**Comment by miguelao** [comment]
Just like in https://github.com/w3c/mediacapture-record/issues/106, https://github.com/miguelao/mediacapture-image/tree/pr_9_bikeshed has a index2.bs (compiled to index2.html) with a BikeShed equivalent of the current Spec status.

Quoting myself, 
> I guess what we'd need to do now is to
>
> move the .bs file to a resurrected master branch,
> modify travis.yml to run a deploy.sh
> generated and add a file deploy_key.enc
> add a deploy.sh like, e.g. https://github.com/WICG/media-capabilities/blob/master/deploy.sh
> Am I missing anything? How can we generate the key, @dontcallmedom ?

**Comment by miguelao** [comment]
@dontcallmedom and I had a small conversation outside and decided to migrate to .bs directly on the `gh-pages` branch and upload the compiled corresponding html file together, not using any Travis magic.  If we see that this is not cool, we can revisit some Travisification of the process.

**Comment by alvestrand** [comment]
Idea:
One nice trick could be to make travis generate the HTML and check that it is equal to the HTML in the PR - essentially checking that the submitter remembered to generate and check in the HTML file after his last change.
At least the submitter will have somewhere to look for the warning when he forgets.

**Comment by miguelao** [comment]
Landed bikeshed version, please take a look and shout out if differences/surprises were to arise.
