### ISSUE TITLE
PhotoCapabilities::autoWhiteBalanceMode is a MediaSettingsItem, could be boolean

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#14]
In [1] , ```autoWhiteBalanceMode``` is described as:
> This reflects whether automated White Balance Mode selection is on or off, and is boolean - on is true

So I would propose making it ```Boolean``` instead of ```MediaSettingsItem```.

The equivalent ```autoWhiteBalanceMode``` setting in ```PhotoSettings``` [2] is a boolean.

[1] http://w3c.github.io/mediacapture-image/index.html#attributes-4
[2] http://w3c.github.io/mediacapture-image/index.html#dictionary-photosettings-members

**Comment by miguelao** [comment]
Same thing for ```redEyeReduction``` in the same ```interface```.

**Comment by gmandyam** [comment]
Yes, these should be Boolean types.  Thanks for the catch.  Have incorporated PR.
