### ISSUE TITLE
Add a way to get stream raw pixels

### ISSUE THREAD

**Issue by fathyb** [w3c/mediacapture-image#147]
`ImageCapture` lacks a way of getting raw camera pixels, I currently use `glTexImage2D`+`glReadPixels` but it's not efficient because of GPU synchronization and the slow frame roundtrip. I also tried `drawImage`+`getImageData` as said in the current draft but it's only 1ms better on my computer and two times slower on most Android phones.

`ImageBitmap` are great for onscreen stuffs, but they do not provide an efficient way to process the camera data on the CPU, for a barcode reader for example.
I do not think we should replace it with `ImageData` (again) but maybe provide both.

We could have two function, `grabFrame` and `grabImageData`, where `grabFrame` triggers (maybe?) and upload to the GPU and then return an `ImageBitmap` and `grabImageData` triggers a CPU read and then return an `ImageData`, as most (if not all?) camera drivers store there frame in the CPU memory.

The problem with `ImageData` being that if it's allocated each frame it could cause GC freezes.

An other solution would be to provide a way (asynchronously?) to get an `ImageData` from an `ImageBitmap`, the vendors could then efficiently store both if needed and prevent a useless roundtrip.

**Comment by gmandyam** [comment]
@fathyb 

Can an ImageBitmap extension be defined for your use case?  See http://kakukogou.github.io/spec-imagebitmap-extension/.

**Comment by fathyb** [comment]
@gmandyam 

Thank you for the reference. Yes, this extension already perfectly answers my use case and I think most of post-processing cases.

I see this is not part of the W3C GitHub account, is there any plans to integrate it? I'm sorry I'm not familiar with the W3C process.

**Comment by gmandyam** [comment]
@fathyb 
As per the Foxeye discussion (https://bugzilla.mozilla.org/show_bug.cgi?id=1141979), there is some effort to bring this into the MediaCapture-Worker specification (see open issues 42 and 45 in https://github.com/w3c/mediacapture-worker/issues).  You could file issues there.

I will be closing this issue for now.  If you think there is something that ImageCapture needs to be looking into re: ImageBitMap Extensions, then feel free to re-open.
