### ISSUE TITLE
Captured image must not expose privacy sensitive information

### ISSUE THREAD

**Issue by alexshalamov** [w3c/mediacapture-image#153]
The resolved promise from takePhoto() method contains data that might expose privacy sensitive information, for example, geolocation, author name, etc.

Therefore, the spec should explicitly state that exif / xmp data (metadata) in the captured image MUST not contain privacy sensitive information. Maybe in “Security and Privacy” section, as it is done in other specifications.

**Comment by gmandyam** [comment]
To @alexshalamov :

@dontcallmedom pointed out that the following text appears in the HTML Media Capture spec (https://www.w3.org/TR/html-media-capture/#security):  

"Implementors should take care to prevent additional leakage of privacy-sensitive data from captured media. For instance, embedding the user’s location in the metadata of captured media (e.g. EXIF) might transmit more private data than the user is expecting."

Would this suffice?

**Comment by alexshalamov** [comment]
@gmandyam Thanks for looking. I think it is sufficient, maybe reference to media capture security section would be nice to have in the future. I will close the issue.

**Comment by dontcallmedom** [comment]
I suggest we leave this open until there is text merged in the spec to that effect

**Comment by gmandyam** [comment]
See https://github.com/w3c/mediacapture-image/pull/155.

**Comment by alexshalamov** [comment]
@gmandyam thanks, looks good.
