### ISSUE TITLE
Provide API for getting / setting metadata

### ISSUE THREAD

**Issue by alexshalamov** [w3c/mediacapture-image#154]
**Getting metadata**

At the moment, if  ‘auto’ photo settings are provided, there is no easy way to obtain information about parameters selected by the camera. Web developers would need to analyze blob by looking for jfif app markers and implementing exif / xmp parser.

**Setting metadata**

If API would provide way of getting metadata, web developers could fill missing parts if needed. For example, developers might want to use Geolocation API to set geolocation data, add author name or tags (keywords) related to the photo.

```
Promise<Photo> takePhoto();
[NoInterfaceObject]
interface Photo : Blob {
  readonly attribute PhotoMetadata metadata;
  void saveMetadata(PhotoMetadata metadata);
};
```

**Comment by gmandyam** [comment]
@alexshalamov 

Editing EXIF data directly was not contemplated to be part of the spec, but there seems to be platform support.  An alternative would be to have a PhotoSetting that disables specific EXIF features, for instance boolean enableGeoTagging.  Would that be a reasonable alternative?

**Comment by alexshalamov** [comment]
@gmandyam 
> boolean enableGeoTagging. Would that be a reasonable alternative?

It will solve issue, partially, yet introduce side-effects. If `enableGeoTagging = true;` UA would need to show Geolocation permission UI, since the geolocation would be exposed and can be easily read, e.g. with exif.js.

I think it would be preferable to split geolocation data accusition and it's setters for the captured image.

```
navigator.geolocation.getCurrentPosition(pos => {
  imgCap.takePhoto().then(photo => { photo.saveMetadata({geolocation: pos}); })
});
```
In this way, permission related functionality would be controlled by Geolocation API.

As for getting image metadata, developers need external js libraries for parsing blob to get information about result of 3A algorithms. I think it would be nice to provide such information in Image Capture API.

**Comment by riju** [comment]
Tentatively closing this, we can re-open/ work on this if there is sufficient customer interest.
