### ISSUE TITLE
redEyeReduction as a sequence<boolean> is strange

### ISSUE THREAD

**Issue by domenic** [w3c/mediacapture-image#156]
Why not just an enum, e.g. "never", "always", "controllable" or similar?

**Comment by miguelao** [comment]
During the change to Constrainable Pattern we also updated this [capability](https://w3c.github.io/mediacapture-image/#dom-photocapabilities-redeyereduction), it reads now:
> If the source cannot do red eye reduction a single false is reported. If red eye reduction cannot be turned off, a single true is reported. If the script can control the feature, the source reports a list with both true and false as possible values.

Which is similar to what's done for [echoCancellation](https://w3c.github.io/mediacapture-main/#dom-mediatrackcapabilities-echocancellation) capability in medicapture-streams Spec and was timely suggested by @jan-ivar.

**Comment by domenic** [comment]
Yes, I was saying that how it reads now is very strange, instead of using an enum. I guess if the idea is to align with another very strange API maybe that is worthwhile, but I am still not sure it is the right tradeoff.

**Comment by jan-ivar** [comment]
@miguelao Actually, since `redEyeReduction` is a photoCapability, not a [Constrainable-Pattern](https://w3c.github.io/mediacapture-main/#capabilities)-using MediaTrackCapability, there's no technical reason it can't use enums or any API it wants. In fact, being different may be a benefit, to avoid confusing the two APIs. Sorry I missed this in review.

**Comment by miguelao** [comment]
@jan-ivar what do you propose? An enum saying e.g.
```
enum redEyeReductionCapability {
  "unsupported",
  "fixed_false",
  "fixed_true",
  "configurable"
};
```
Or some such?

**Comment by jan-ivar** [comment]
@miguelao What's the difference between `"unsupported"` and `"fixed_false"`?

I liked @domenic's `"never"`, `"always"`, `"controllable"`.

**Comment by miguelao** [comment]
`"never"`, `"always"`, `"controllable"` it is! 👍

**Comment by miguelao** [comment]
Closing by PR #165 .
