### ISSUE TITLE
Provide API for getting / setting focus distance

### ISSUE THREAD

**Issue by alexshalamov** [w3c/mediacapture-image#158]
The API allows to set manual focus mode, yet, there is no way to set focus distance manually. Maybe API can provide interface for getting focus range values as well as setting focus distance value.

**Comment by dsanders11** [comment]
I'd like to bump this and voice my support for this as well. What is the current use case of setting `focusMode` to `manual` if you can't then provide a focus value? What focus value will be used, the last value before it was changed from auto to manual?

I have a strong use case for this API, and it could more or less be a drop-in replacement if a manual focus value is added to the API. Without a way to set a manual focus value it is not very useful as I have a use case where the user calibrates the camera settings once (sets zoom and focus value) and those settings are reloaded every time the page is used to provide a consistent experience as far as zoom and focus go. Currently this is accomplished in a hacky way by using WebSockets to talk to a server on the local machine which uses low-level APIs to set these values. I know that UVC and Windows APIs both have support for setting a manual focus value. The `android.hardware.camera2` API appears to have support for setting a focus distance, it's unclear if the older `android.hardware.Camera` API does.

@miguelao, anything I can do to help add this functionality to the spec?

**Comment by yellowdoge** [comment]
Closing since the conversation has moved to #176 and its associated PR #175.
