### ISSUE TITLE
grabFrame() should probably not use or refer to photoSettings

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#16]
Method ```grabFrame()``` is described [1] as:
>  [...] The method of doing this will depend on the underlying device. Devices may temporarily stop streaming data, reconfigure themselves with the appropriate photo settings (which may be a subset of the settings provided in photoCapabilities), take the photo (and convert to an ImageBitmap object), and then resume streaming.

where the ```takePhoto()``` description nearby [2] is:
> [...] The method of doing this will depend on the underlying device. Devices may temporarily stop streaming data, reconfigure themselves with the appropriate photo settings, take the photo, and then resume streaming.

The ```grabFrame``` description of the underlying device being reconfigured is misleading and cites a function parameter (the ```photo settings```) which is not present.

Consider making explicit that ```grabFrame()``` should simply grab the VideoFrame verbatim from the MediaStreamVideoTrack; this is hinted by the comment ```The width and height of the ImageBitmap object are derived from the constraints of the MediaStreamTrack. ```. 

[1] http://w3c.github.io/mediacapture-image/#widl-ImageCapture-grabFrame-Promise-ImageBitmap
[2] http://w3c.github.io/mediacapture-image/#widl-ImageCapture-takePhoto-Promise-Blob

**Comment by gmandyam** [comment]
It was actually unresolved as to whether grabFrame would be affected by photo settings.  It seems like it should not be, given that the ImageBitMap object returned would be subject to post-processing.  Have incorporated the corresponding pull request.  Thanks.
