### ISSUE TITLE
Provide way to get / set captured image format

### ISSUE THREAD

**Issue by alexshalamov** [w3c/mediacapture-image#162]
Would be nice to have an API / setting that will provide zero shutter lag support. For example, after setting that parameter in PhotoSettings, takePhoto would return YUV blob that can be sent back to camera for processing in order to get, e.g., jpg image.

`imgCap.takePhoto().then( photo => { imgCap.process(photo); } ).then(jpg => {saveJpg(jpg)});`

**Comment by miguelao** [comment]
[`grabFrame()`](https://w3c.github.io/mediacapture-image/#dom-imagecapture-grabframe) does precisely that, by simply 'grabbing' the next frame passing by the source MediaStreamTrack.

**Comment by alexshalamov** [comment]
@miguelao This issue is about different use-case, by avoiding image processing pipeline in camera stack, end user would have possibility to access 'raw' image. This will allow to reduce shutter lag latency, but might require additional API to send image back to the stack that will return converted image. Do you mind if I re-open the issue?

**Comment by alexshalamov** [comment]
If I understand correctly grabFrame()  just grabs frame from preview surface, it provides instant capture, yet, for proper 'raw' capture, I think takePhoto with additional setting is still required.

**Comment by miguelao** [comment]
Let's reopen then.

**Comment by miguelao** [comment]
IIUC your concern is with accessing RAW images from the sensor, is this correct? (If so, could you please rename the bug?)  

If that'd be the case, it could be supported via some extension to the [`PhotoCapabilities`](https://w3c.github.io/mediacapture-image/##photocapabilities-section)
```
interface PhotoCapabilities {
  ...
  readonly attribute FrozenArray<DOMString>       supportedImageFormats;
};
```
and a similar entry to the [`PhotoSettings`](https://w3c.github.io/mediacapture-image/##photosettings-section) dictionary, e.g. 
```
dictionary PhotoSettings {
  ...
  DOMString   imageFormat;
};
```
`takePhoto()` would return a `Blob` with the [`type`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/type), e.g. `image/x-adobe-dng` or `image/tiff`.  

Would that address your use case?

**Comment by alexshalamov** [comment]
@miguelao I renamed the issue.

**Comment by yellowdoge** [comment]
@alexshalamov could you please write a PR with the API you'd like to see, perhaps based on https://github.com/w3c/mediacapture-image/issues/162#issuecomment-290152484?

**Comment by alexshalamov** [comment]
@yellowdoge Sure, I will create PR.

**Comment by Fuzzyma** [comment]
When we have this, we also need something to set the quality of the image taken.
`<canvas>`s `toBlob()` method let us specify a mimetype as well as a quality. Why not having it here?
Mostly I dont need jpg images with 100% quality

**Comment by alexshalamov** [comment]
@Fuzzyma good point. If quality adjustment is required, then it should be bundled together with type, e.g., if type is tiff or raw `MediaSettingsRange` for quality setting would be `{ min:100,  max: 100,  step: 0 }`

@yellowdoge what do you think? I tried to draft IDL with `dictionary ImageFormat` :
```
  interface PhotoCapabilities {
    readonly attribute FrozenArray<ImageFormat> supportedImageFormats;
  };

  dictionary PhotoSettings {
    ImageFormat       imageFormat;
  };

  dictionary ImageFormat {
    DOMString           type;
    MediaSettingsRange  quality;
  };
```

Then there is a problem with` FrozenArray<ImageFormat>` in `PhotoCapabilities`, :disappointed:

**Comment by Fuzzyma** [comment]
The other way would be to have it as optional key of `PhotoSettings` that is ignored when compression of the selected format is not supported.

**Comment by alexshalamov** [comment]
@Fuzzyma sure, could be simpler option. Dictionary members are optional by default.

**Comment by alexshalamov** [comment]
@Fuzzyma would #186 be sufficient?

**Comment by Fuzzyma** [comment]
Yes that looks great! Thank you!

**Comment by riju** [comment]
I am tentatively closing this issue now, as we don't want it to be considered for the wide review of this spec. If there are customers who feel this feature is a necessity, we can definitely reopen and work on this further more on top of https://github.com/w3c/mediacapture-image/pull/185

**Comment by SaharHusseini** [comment]
Hello,

I'm reaching out with a question regarding obtaining RAW image data using mediaCapture. I'm interested in capturing raw images, but being new to media capture and HTML, I find it challenging to integrate extensions into the base code. Could you please provide beginner-friendly advice on how to capture RAW image data using mediaCapture?

Thank you!
