### ISSUE TITLE
Pan and Tilt Constraints

### ISSUE THREAD

**Issue by dsanders11** [w3c/mediacapture-image#177]
What are the feelings on adding a pan constraint and a tilt constraint?

Both settings are part of the UVC spec. They're supported on Windows ([getRange_Pan](https://msdn.microsoft.com/en-us/library/windows/desktop/dd376305(v=vs.85).aspx) and [getRange_Tilt](https://msdn.microsoft.com/en-us/library/windows/desktop/dd376309(v=vs.85).aspx)) and via V4L2 on Linux (`V4L2_CID_PAN_ABSOLUTE` and `V4L2_CID_TILT_ABSOLUTE`).

They do not, however, appear to be supported on Android via either API (`android.hardware.camera` or `android.hardware.camera2`). Most built-in cameras on Android devices likely don't support them anyway, from my experience.

Logitech webcams support pan and tilt and it would be a great resource to have in the spec for fully controlling these types of cameras.

**Comment by dsanders11** [comment]
@yellowdoge, thoughts? I do see in [this commit](https://chromium.googlesource.com/chromium/src/media/+/41dba5eecb31f0d2b040623f6fa8dafd4f102384) you mentioned "Avoid reset PAN/TILT controls due to Image Capture API not giving access
to them (yet)" so it sounds like you're in favor of adding the controls to the spec.

Anything learned there with V4L2 that makes the implementation seem too tricky to tackle at the moment?

**Comment by yellowdoge** [comment]
Yeah, there's a private webcam extension ([code](https://cs.chromium.org/chromium/src/extensions/browser/api/webcam_private/?q=extensions/browser/api/webcam_private&sq=package:chromium&dr)), essentially a JS-surfaced IDL directly touching the filesystem `/dev/videoX` to manipulate zoom, pan and tilt for certain cameras ([more code](https://cs.chromium.org/chromium/src/extensions/browser/api/webcam_private/v4l2_webcam.cc?sq=package:chromium&dr&l=18)).   The issue that prompted that commit was to avoid resetting those controls because the clients of this extension API relied on the V4L2 API persisting the configuration values.

**Comment by dsanders11** [comment]
Would that pose a large problem for adding pan and tilt constraints, or does it seem possible to work around?

**Comment by yellowdoge** [comment]
I think the private api should not prevent consensus and addition to the spec of this new capabilities/constraints, but from the point of view of the implementation, we should have a way to allow those users and easy migration and right now they rely on the UVC camera to store the last configured state (except across reboots).  Such path could be provided via a method to return constraints to their default values; a [discussion](https://github.com/w3c/mediacapture-main/issues/438) did not really clarify to me if `applyConstraints()` (with an empty dictionary) would clear all constraints (which would cover my needs), or do nothing at all :-)

@jan-ivar, wdyt?

**Comment by jan-ivar** [comment]
Yes `applyConstraints({})` removes all *your* constraints, leaving the device "unconstrained" if you are the only user. Other tabs may be accessing the same device, but barring that edge-case, the API should¹ play well with outside controls (which could even be a web api in a different tab).

As to "default values", constraints is a device settings API. Device setting defaults may vary from browser to browser, device to device, or even the situation, so never rely on them. If you care about a setting, constrain it.

<sub>1. In theory. The browser is the ultimate owner of the device. How well it plays with others depends.</sub>

**Comment by dsanders11** [comment]
@yellowdoge, @jan-ivar, unless any reasons not to, I'll go ahead and make a PR adding pan and tilt to the spec, after the focus distance PR is finished (still waiting on IPR stuff).

**Comment by yellowdoge** [comment]
Ofc, please go ahead, we'll debate over the PR.
