### ISSUE TITLE
Add image quality member to PhotoSettings dictionary

### ISSUE THREAD

**Issue by alexshalamov** [w3c/mediacapture-image#186]
This will allow setting image quality for the captured photo.

```
dictionary PhotoSettings {
  ...
  [Clamp] unsigned short imageQuality = 100;
};
```
The imageQuality is in range of [0-100] %
If the quality of the format for the captured image cannot be set, UA MAY omit this setting.

**Comment by riju** [comment]
Closing this as of now. We can re open this once there is explicit customer requirement.

**Comment by Fuzzyma** [comment]
@riju how is "customer requirement" defined?
