### ISSUE TITLE
"If the UA is unable to execute the getPhotoSettings() method for any reason"

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-image#188]
https://w3c.github.io/mediacapture-image/#dom-imagecapture-getphotosettings

The meaning here is clear, but at this point in the algorithm getPhotoSettings() has already returned, it has already been executed. Instead it could say "If the UA is unable to gather the data for any reason", perhaps.

**Comment by yellowdoge** [comment]
Should be ok now. If you want me to make `data` a `<var>data</var>`  in the phrases:

> Gather data from {{track}} into a ...
> ...
>If the UA is unable to gather the data

at https://github.com/w3c/mediacapture-image/blob/master/index.bs#L177

just reopen this issue please.

**Comment by foolip** [comment]
Thanks, LGTM.
