### ISSUE TITLE
Sort out fingerprint surface

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-image#198]
From https://lists.w3.org/Archives/Public/public-media-capture/2018Feb/0005.html:
"MediaStream Image Capture primarily refers to getUserMedia for security/privacy considerations. There is at least one mention in the spec about a fingerprinting surface mitigation (in using ranges on image height and width), but I'm not clear on the particular risk and its mitigation. Do the other capabilities and constrainable properties also add to fingerprinting surface? Is EXIF data (mentioned in the privacy considerations section) specified by this document?"
Two specific questions: 
- Do the other capabilities and constrainable properties also add to fingerprinting surface? 
- Is EXIF data (mentioned in the privacy considerations section) specified by this document?

**Comment by yellowdoge** [comment]
Related to #172

**Comment by riju** [comment]
Covered by [Security and Privacy questionnaire](https://github.com/w3c/mediacapture-image/blob/master/security-privacy-questionnaire.md)
