### ISSUE TITLE
Implementation status using torch on chrome under Windows 10

### ISSUE THREAD

**Issue by benag** [w3c/mediacapture-image#202]
Hi,
I am trying to use torch to turn on flash light when taking pictures.
Looking at tutorials it is my understanding that track.getCapabilities() should show the torch capability in order to use it. However the torch true is not present when calling the above API.
I am getting:
[
![torch](https://user-images.githubusercontent.com/4804543/51172372-ca178200-18bb-11e9-98d8-ad27c08b76be.PNG)

My OS is windows 10 Enterprise on Panasonic tablet.

Thank you,
Ben

**Comment by xelaz** [comment]
I can enable torch mode on android in this way:
```
    try {
      const track = stream.getVideoTracks()[0];
      const torch = !torchMode;
      track.applyConstraints({
        advanced: [{ torch }],
      });
    } catch (_) {
      // torch is not available
    }
```

**Comment by benag** [comment]
Running your code inside the timeout () i am getting the same result torch is not in capabilities.

**Comment by alvestrand** [comment]
Please file a bug on the browser you're using. This bug tracker is for issues with the spec, not issues with the implementations.

**Comment by yellowdoge** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=922184, please follow up there folks.
