### ISSUE TITLE
Clarify applicability of MediaTrackSupportedConstraints

### ISSUE THREAD

**Issue by reillyeon** [w3c/mediacapture-image#206]
This specification [extends the MediaTrackSupportedConstraints dictionary](https://w3c.github.io/mediacapture-image/#mediatracksupportedconstraints-section) with additional constraints as follows,

> MediaTrackSupportedConstraints is extended here with the list of constraints that a User Agent recognizes for controlling the photo capabilities.

Readers of this specification have mistakenly assumed that this means that these constraints only apply when capturing a single image using the `takePhoto()` API and not to the MediaStreamTrack as a whole. This makes the API appear unsuitable for controlling features such as pan, tilt and zoom for video streams when in fact it is.

**Comment by riju** [comment]
The introduction section says

> Reading capabilities and settings and applying constraints is done in one of two ways depending on whether it impacts the video MediaStreamTrack or not. Photo-specific capabilities and current settings can be retrieved via getPhotoCapabilities()/getPhotoSettings() and configured via takePhoto()'s PhotoSettings argument. Manipulating video-related capabilities, current settings and constraints is done via the MediaStreamTrack extension mechanism.

If needed, we can add a Note for further clarification.
Constraints that apply to the live video feed are in [MediaTrackSettings](https://w3c.github.io/mediacapture-image/index.html#mediatracksettings-section) and constraints that **only** apply when capturing image using `takePhoto()` are handled by [PhotoSettings](https://w3c.github.io/mediacapture-image/index.html#photosettings-section).
