### ISSUE TITLE
Consider adding provisions for live display of capture Options 

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#21]
In the current Spec, the method [```setOptions()```](http://w3c.github.io/mediacapture-image/#widl-ImageCapture-setOptions-Promise-void--PhotoSettings-photoSettings) applies a series of picture settings whose result can only be seen after taking a Picture with [```takePhoto()```](http://w3c.github.io/mediacapture-image/#widl-ImageCapture-takePhoto-Promise-Blob). It would be great if those options could be applied 'live' and the result seen as they are applied. For instance, focus mode, flash/torch mode (on/off), or colour temperature. This might not be possible throughout since those options could be applicable only during photo exposure mode (and not, e.g. in preview mode), but those Options where it makes sense, we should find a way.

**Comment by gmandyam** [comment]
@miguelao 

Is this issue still applicable?  It is possible now to apply settings to takePhoto.  Presumably the preview stream would reflect the changes as the picture is being taken.

**Comment by miguelao** [comment]
I think `previewStream` should cover pretty much my concern. Only perhaps the wording could hint to that in the description of `setOptions()`, will give it a go.
