### ISSUE TITLE
"Tap to auto-focus" feature

### ISSUE THREAD

**Issue by josephernest** [w3c/mediacapture-image#217]
[focus-mode](https://w3c.github.io/mediacapture-image/#focus-mode) has currently two modes:

* either  `manual` (set with `focusDistance`)
* or `auto` in which everything is automatic

For many applications, a "tap on screen to redo auto-focus" would be helpful or even mandatory (e.g. camera web app, barcode reader, etc.).

This is often the default and mostly-used focus method in main camera smartphone applications:

* autofocus
* the user can tap on screen to force re-focus

Do you think this standard feature could be available in [focus-mode](https://w3c.github.io/mediacapture-image/#focus-mode)?

Related: https://stackoverflow.com/questions/60188128/tap-screen-to-trigger-autofocus-with-getusermedia

**Comment by riju** [comment]
Not many platforms support Tap to auto-focus (say not Android), so we might not consider this as part of the spec at this current time.
