### ISSUE TITLE
Consider converting attribute PhotoCapabilities into a getCapabilities() method

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#22]
```ImageCapture``` has a [```readonly attribute PhotoCapabilities photoCapabilities;```](http://w3c.github.io/mediacapture-image/#image-capture-api), that is defined further on ([here](http://w3c.github.io/mediacapture-image/#photocapabilities)) as:

> The photoCapabilities attribute of the ImageCapture object provides the photo-specific settings options and current settings values.

Retrieving and updating such a field is inherently racy with the rest of the Web Platform code, so I propose converting this ```attribute``` into a ```Promise<PhotoCapabilities> getCapabilities(); [Throws]```, so basically the user/developer can control when/how often these numbers are retrieved, in an asynchronous way.

**Comment by miguelao** [comment]
I meant:
```[Throws] Promise<PhotoCapabilities> getCapabilities();```

**Comment by gmandyam** [comment]
Have merged https://github.com/w3c/mediacapture-image/commit/000ef74f832637d5f0956db5de780936e789181b into spec, but still need to address what would be returned in case promise fails to resolve.

**Comment by miguelao** [comment]
@gmandyam, does the current reading of [getPhotoCapabilities()](https://w3c.github.io/mediacapture-image/#dom-imagecapture-getphotocapabilities) address your concern?  (Now: a Promise is rejected with `InvaIidStateError` or `OperationError`).

**Comment by gmandyam** [comment]
@miguelao Current spec addresses my concerns.  Closing issue.
