### ISSUE TITLE
Sanitize PTZ capabilities/settings based on PTZ permission

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#245]
As raised by @youennf in https://github.com/w3c/mediacapture-image/issues/243#issuecomment-674027572, the spec should say clearly that PTZ capabilities are not available when PTZ permission is not granted. Same for PTZ settings.

@eehakkin Can you take care of this?

**Comment by youennf** [comment]
To be clear, it might be ok to allow web page to know that a selected camera has PTZ so that web page asks more permission to user. This is up to discussion but the spec should clearly specify it either way.

For PTZ settings, spec should clearly mandate sanitization.

**Comment by beaufortfrancois** [comment]
For info, Chromium implementation sanitizes PTZ capabilities and settings based on PTZ permission.

**Comment by youennf** [comment]
The particular case of PTZ capabilities seems worth getting input from the WebRTC WG.

**Comment by eehakkin** [comment]
So the corresponding pull request is https://github.com/w3c/mediacapture-image/pull/248.

**Comment by eehakkin** [comment]
> As raised by @youennf in [#243 (comment)](https://github.com/w3c/mediacapture-image/issues/243#issuecomment-674027572), the spec should say clearly that PTZ capabilities are not available when PTZ permission is not granted. Same for PTZ settings.

The both changes have now been merged.

**Comment by beaufortfrancois** [comment]
Thanks! I'll close it.
@youennf Feel free to re-open if there's something we've missed.

**Comment by jan-ivar** [comment]
This issue has a resolution associated with it in the [minutes](https://www.w3.org/2020/09/15-webrtc-minutes.html#r06) so I think it should remain open until its PR has been merged.
