### ISSUE TITLE
Stop referring to `advanced` constraints

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-image#252]
This spec refers to the overly complex and outdated [advanced](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-constraints-advanced) constraints syntax in:
1. [examples](https://w3c.github.io/mediacapture-image/#examples)
2. In issues like https://github.com/w3c/mediacapture-image/issues/243#issuecomment-674090590, where apparently one browser infers new meaning from their presence

The former is unnecessary, and the latter is a non-standard.

The differences between the older `advanced` constraints and the modern `ideal` constraints are [minimal](https://w3c.github.io/mediacapture-main/getusermedia.html#example-3) and best forgotten. TL;DR: they allowed for non-linear fallbacks between `width` x `height` x `frameRate` combos when `resizeMode` is `none`. They're largely redundant elsewhere, since most other constrainable capabilities are orthogonal to each other.

It's therefore best to not mention them, to discourage use. Maybe one day we'll be able to remove them from the platform.

**Comment by beaufortfrancois** [comment]
How would we differentiate an optional PTZ request without advanced constraints?
See explainer.

(Sorry I'm on mobile and ooo this week)

**Comment by jan-ivar** [comment]
@beaufortfrancois show me where in the spec `advanced` constraints let you do that.

**Comment by jan-ivar** [comment]
@beaufortfrancois note constraints are non-required by default, so this should suffice:
```js
{video: {pan: true, tilt: true, zoom: true}}
```

**Comment by jan-ivar** [comment]
Here's a good example of why `advanced` constraints suck: a likely bug in [ptz-explainer.md](https://github.com/w3c/mediacapture-image/blob/master/ptz-explainer.md#control-camera-pantilt):
```js
const videoStream = await navigator.mediaDevices.getUserMedia({
  video: {
    advanced: [{
      // [NEW] Website asks to control camera PTZ as well.
      pan: true, tilt: true, zoom: true,
    }],
  },
});
```
The above will, if the [constraints algorithm](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-selectsettings) is implemented correctly, only discover cameras that have _**all three capabilities**_.
If none exists, it'll return any regular camera (possibly forgoing cameras that have _some_ of these abilities but not all).

To get cameras with one or more of the `pan`, `tilt` and `zoom` abilities would instead have to be written like this:
```js
  video: {
    advanced: [
      {pan: true},
      {tilt: true},
      {zoom: true}
    ],
  }
```
...or simply:
```js
  video: {pan: true, tilt: true, zoom: true}
```

**Comment by jan-ivar** [comment]
MDN has a good [constraints explainer](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Parameters).

**Comment by reillyeon** [comment]
Based on the above it sounds like we want to define something like this to support mandatory PTZ constraints:

```js
const videoStream = await navigator.mediaDevices.getUserMedia({
  video: {pan: {exact: true}, tilt: {exact: true}, zoom: {exact: true}}
});
```

I think this makes sense if we make these properties `ConstrainBoolean or ConstrainDouble` instead of `boolean or ConstrainDouble`.

**Comment by jan-ivar** [comment]
That would seem to run counter to https://github.com/w3c/mediacapture-image/issues/246.

**Comment by reillyeon** [comment]
Agreed, though that seems to make the use of `ConstrainDouble` also problematic as setting `'min'` or `'max'` would also create a required constraint.

Focusing on the intention of this design, the reason for the `true` value is to make it possible for a site to declare that it wants to control pan, tilt, and/or zoom without specifying any particular value. This is important as before `getUserMedia()` returns the site doesn't know what the supported settings range is or what the current position of the camera is and so no value is appropriate to pass in the initial `getUserMedia()` call. `true` is used as a sentinel instead to simply indicate the desire to potentially control this setting in the future..

**Comment by jan-ivar** [comment]
Yes but `true` is also merely an alias for`{}` which already works; a nicety we added to promote the pattern you mention.

Using required constraints that way is not a pattern we want to promote (or with https://github.com/w3c/mediacapture-image/issues/246 even make possible).

**Comment by beaufortfrancois** [comment]
IIUC, the presence of a pan, tilt or zoom constraint **without** an explicit min/man/exact should be an **optional** request of capability/permission whether it is an basic or advanced set; and **with** an explicit min/man/exact it should be a **mandatory** request for capability/permission whether it is an basic or advanced set.

Note that in advanced set, the lack of PTZ capability just means that the advanced set will be ignored, not that the PTZ request will fail. This means permission shouldn't be asked when in an advanced set and no capability.

If that looks good to you, we'll update spec and explainer.

**Comment by jan-ivar** [comment]
> IIUC, the presence of a pan, tilt or zoom constraint without an explicit min/man/exact should be an optional request

No it doesn't, as I point out in https://github.com/w3c/mediacapture-image/issues/256. I think we should fix that with option 3 in that proposal.

Only then would what I wrote [above](https://github.com/w3c/mediacapture-image/issues/252#issuecomment-679346614) actually be true:
> @beaufortfrancois note constraints are [non-required](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-optional-basic-constraints) by default, so this should suffice:
> ```js
> {video: {pan: true, tilt: true, zoom: true}}
> ```

**Comment by riju** [comment]
I think if we go down the path of https://github.com/w3c/mediacapture-image/issues/256#issuecomment-687111563, we would not need advanced constraints

**Comment by beaufortfrancois** [comment]
@riju I believe we can close this issue as we chose to only allowing ideal PTZ constraints in the basic set, and discarding mandatory PTZ constraints in advanced sets.
See https://github.com/w3c/mediacapture-image/pulls
