### ISSUE TITLE
Consider adding parameter PhotoSettings? parameter to method takePhoto()

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#27]
Method [`setOptions()`](https://w3c.github.io/mediacapture-image/#widl-ImageCapture-setOptions-Promise-void--PhotoSettings-photoSettings) applies a series of `PhotoSettings` to Picture(s) taken with `takePhoto()`. With the current scheme, the given `PhotoSettings` are to be sticky and stay around to take effect in posterior `takePhoto()` call(s). To provide better API orthogonality, I'ld suggest adding the same parameter `PhotoSettings` to `takePhoto()`, so configuration and picture-taking can happen simultaenously.

**Comment by gmandyam** [comment]
Addressed by PR https://github.com/w3c/mediacapture-image/pull/37/commits/c3994b314fb77170d22757233f1f14886d70f012
