### ISSUE TITLE
Should we treat PTZ constraints given to getUserMedia as booleans

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-image#270]
Following on TPAC meeting, it seems there is a desire to have a model where pan, tilt and zoom constraints given to getUserMedia are for device selection. It would be thus recommended to pass booleans there.
For applyConstraints however, given the device is already selected, it makes sense to not pass boolean but pass numerical values. It would be thus recommended to pass numerical values there.

We should probably make it clear in specs and examples that this is the recommended way.
We could also decide to mandate that behavior in the spec and always treat pan tilt zoom constraints in getUserMedia as if they are true whenever present.

**Comment by murillo128** [comment]
I don't knot the background of the discussion so maybe I am missing something, but anyway.

Having params boolean values in gUM for PTZ seems correct, but I would recommend changing the name of the attributes to avoid confusion, something like `zoomSupported`,`tiltSupported` and `panSupported`. May require to refactor the dictionaries though.

**Comment by jan-ivar** [comment]
This was addressed by https://github.com/w3c/mediacapture-image/pull/271 and https://github.com/w3c/mediacapture-main/pull/766.
