### ISSUE TITLE
Inability to turn off torch with track applyConstraints

### ISSUE THREAD

**Issue by shieldsyWRH55** [w3c/mediacapture-image#275]
I had been using a video stream in a QR code scanner web application. Originally the user could toggle the torch on mobile devices. Recently this has become broken and now I am no longer able to turn the torch off after it has been turned on. 

Setting the torch constraint to false using this piece of javascript code no longer works. However, will work the very first time when setting the torch to true. 

this.$video.srcObject.getVideoTracks()[0].applyConstraints({
            advanced: [{ torch: on }]
});

_**on** is a passed in boolean_

**Comment by dontcallmedom** [comment]
(transferred to the Image Capture spec where the torch constraint is defined)

**Comment by shieldsyWRH55** [comment]
@dontcallmedom Thanks a lot.

**Comment by eehakkin** [comment]
This seems to be a coding error in https://github.com/sabitertan/BlazorBarcodeScanner/blob/master/BlazorBarcodeScanner.ZXing.JS/wwwroot/BlazorBarcodeScanner.js discussed in sabitertan/BlazorBarcodeScanner#4.

There does not seems to be problems in the spec so closing.
