### ISSUE TITLE
Boolean should be lowercased in WebIDL

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-image#28]
https://w3c.github.io/mediacapture-image/index.html#idl-def-PhotoCapabilities

Here `autoWhiteBalanceMode` and `redEyeReduction` are "Boolean".

(Also the indentation here is very excessive.)

**Comment by gmandyam** [comment]
Fixed by https://github.com/w3c/mediacapture-image/pull/25/commits/86b8ce103dcc7718628ade284ce976d9d6cfaf75

**Comment by gmandyam** [comment]
Reopening.  Having to revert changes to accomodate Miguel's PR.  Will add Boolean type change afterwards.

**Comment by alvestrand** [comment]
OK, my comment on the reverting PR (#33) is addressed here.

**Comment by gmandyam** [comment]
Lower case boolean partially addressed via PR https://github.com/w3c/mediacapture-image/pull/32/commits/7ebe056665b47521f7bdfeecc69d6d520088810e.  Still have additional cleanup.

**Comment by gmandyam** [comment]
Last instances addressed in https://github.com/w3c/mediacapture-image/pull/39/commits/4ac19376ad1e6e0fffaab4784cef94c34c63f629.  Closing issue now.
