### ISSUE TITLE
Should all PhotoCapabilities members be readonly?

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-image#29]
https://w3c.github.io/mediacapture-image/#idl-def-PhotoCapabilities

It doesn't make sense to mutate the values it seems. But why isn't the `PhotoSettings` dictionary used as the return value for `getPhotoCapabilities()`?

**Comment by miguelao** [comment]
`PhotoSettings` is a Dictionary and `PhotoCapabilities` an interface; many items of the former are numbers (e.g. unsigned longs) where the correspondent member in the latter is a range of supported values.

Is there a way to link those two...?

**Comment by miguelao** [comment]
(And, I agree about the read-only-ness, of course).

**Comment by foolip** [comment]
OK, I wasn't paying attention, so capabilities are ranges but settings are specific values, that makes sense.

**Comment by gmandyam** [comment]
Addressed with @miguelao PR:  https://github.com/w3c/mediacapture-image/pull/34/commits/b536dee9d2c508448f5f12121ba41769d3061976
