### ISSUE TITLE
Consider replacing image{Height,Width} with supported and current resolutions

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#30]
`PhotoCapabilities` has two parameters:
```
attribute MediaSettingsRange imageHeight;
attribute MediaSettingsRange imageWidth;
```
which are decoupled from each other, i.e. the first might represent [240..720] and the latter [320..1280]. Usually, supported ranges are enumerated in couples, i.e. as an array of resolutions `{[320, 240], [640, 480], [1280, 720], [640 360]}`. 

I understand that `MediaSettingsRange` includes a `current` field, so a potential alternative could be:
```
attribute sequence<Resolution> supportedResolutions;
attribute Resolution currentResolution;
```
where `Resolution` would essentially be a [TBD] width x height data type.

**Comment by gmandyam** [comment]
Note that this was considered in the early days of the spec, and was not adopted for the following reasons:

a) Providing supported resolutions through API increases device fingerprinting surface
b) Implementations can meet the requested height/width pairing through best effort (i.e. choosing best match among supported resolutions)
c) We did not want to prevent implementations from performing automated resizing, though this may be undesirable in certain instances (e.g. interpolating a supported resolution to meet a height/width request)

**Comment by miguelao** [comment]
I see, it makes sense. Perhaps we could add a NOTE of sorts in the Spec? I can take it.

**Comment by gmandyam** [comment]
Addressed by https://github.com/w3c/mediacapture-image/pull/47/commits/a138febc6cf3909474597764dea272f1525e2d5f
