### ISSUE TITLE
Why is https://www.w3.org/TR/image-capture/#dom-mediatrackcapabilities-torch a boolean

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-image#304]
https://w3c.github.io/mediacapture-main/#dom-mediatrackcapabilities-echocancellation is `[false]`, `[true]` or `[false, true]`.
https://www.w3.org/TR/image-capture/#dom-mediatrackcapabilities-torch is supposed to be `false` or `true`.

It seems we should align these properties, probably torch should align with echoCancellation and other booleans like autoGainControl, noiseSuppression.

@guidou, do you know what Chrome is doing here and/or why a single bool was chosen?
@jan-ivar, thoughts?

**Comment by guidou** [comment]
Chrome has it as a bool, but I think it should be an array.
I don't know why it was done this way, but my guess is that `true` actually means `[false,true]`, given that the definition is

> A boolean indicating whether camera supports [torch](https://www.w3.org/TR/image-capture/#torch) mode- on meaning supported.
