### ISSUE TITLE
Update default branch to gh-pages (ISO master)

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#38]
`master` of this repo is essentially abandoned, whereas `gh-pages` is active and running. Recommend changing the Default branch to `gh-pages` as in e.g. MediaRecorder GitHub repo.

For that, go to the repo "Settings", click on "Branches" on the left hand menu, and select `gh-pages`, see this partial screenshot: [http://imgur.com/PlBxQ9T](url)

**Comment by gmandyam** [comment]
Settings does not show up for me in the W3C repo.  Will see if someone in W3C can address.

**Comment by dontcallmedom** [comment]
I've updated the repo to use `gh-pages` as the default branch .

If master is indeed abandonned, I suggest removing it (which I'm happy to do)

**Comment by gmandyam** [comment]
@dontcallmedom 

Please remove the master branch.  Thanks for your help.

**Comment by dontcallmedom** [comment]
done

**Comment by vivienlacourba** [comment]
I see that the `master` branch has been removed which means this issue can be closed.
