### ISSUE TITLE
Extend `PhotoSettings` to support points/regions of interest for e.g. Auto Focus/Exposure

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#44]
[`PhotoSettings`](https://w3c.github.io/mediacapture-image/#PhotoSettings)  can specify e.g. `FocusMode` and `ExposureMode` but not where in the current scene to use as seeds for either of these.  For example Android provides [regions for autofocus](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#CONTROL_AF_REGIONS) and for [autoexposure](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#CONTROL_AE_REGIONS)), and so does Mac AVFoundation ([autofocus point of interest](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVCaptureDevice_Class/#//apple_ref/occ/instp/AVCaptureDevice/focusPointOfInterest) and [autoexposure point of interest](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVCaptureDevice_Class/#//apple_ref/occ/instp/AVCaptureDevice/exposurePointOfInterest)). Consider adding provisions in `PhotoSettings` to indicate which point(s) or region(s) to use for these operations (probably in a normalized framework, i.e. coordinates ranging in `[0,1)` )

**Comment by gmandyam** [comment]
Addressed by https://github.com/w3c/mediacapture-image/pull/45/commits/d7bc9611057207d25fcef7d187c583a9d130749a
