### ISSUE TITLE
Revisit ExposureMode and FillLightMode data types to better reflect mobile platforms

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#49]
Current [ExposureMode](https://w3c.github.io/mediacapture-image/#ExposureMode)s are typical for DSLR cameras (see e.g. [this article](http://www.digital-photo-secrets.com/tip/2879/which-is-best-spot-center-weight-or-matrix-metering/)):
``` 
enum ExposureMode {
    "frame-average",
    "center-weighted",
    "spot-metering"
};
```
whereas [Fill Light Mode](https://w3c.github.io/mediacapture-image/#FillLightMode)s are:
```
enum FillLightMode {
    "unavailable",
    "auto",
    "off",
    "flash",
    "on"
};
```

These don't correlate strongly for mobile platforms, e.g:

- Android Camera2's [AE modes](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#CONTROL_AE_MODE) and  [flash modes](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#FLASH_MODE):

``` 
CONTROL_AE_MODE_OFF
CONTROL_AE_MODE_ON
CONTROL_AE_MODE_ON_AUTO_FLASH
CONTROL_AE_MODE_ON_ALWAYS_FLASH
CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE
```
```
FLASH_MODE_OFF
FLASH_MODE_SINGLE
FLASH_MODE_TORCH
```

- Mac AVFoundation's [exposure mode](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVCaptureDevice_Class/#//apple_ref/c/tdef/AVCaptureDevicePosition). [flash mode] (https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVCaptureDevice_Class/#//apple_ref/c/tdef/AVCaptureFlashMode) and [torch mode](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVCaptureDevice_Class/#//apple_ref/c/tdef/AVCaptureTorchMode):

``` 
typedef enum : NSInteger {
   AVCaptureExposureModeLocked                    = 0,
   AVCaptureExposureModeAutoExpose                = 1,
   AVCaptureExposureModeContinuousAutoExposure    = 2,
   AVCaptureExposureModeCustom                    = 3,
} AVCaptureExposureMode;
```
```
typedef enum : NSInteger {
   AVCaptureFlashModeOff    = 0,
   AVCaptureFlashModeOn     = 1,
   AVCaptureFlashModeAuto   = 2
} AVCaptureFlashMode;
```

```
typedef enum : NSInteger {
   AVCaptureTorchModeOff    = 0,
   AVCaptureTorchModeOn     = 1,
   AVCaptureTorchModeAuto   = 2
} AVCaptureTorchMode;
```

So I propose:
- removing`FillLightMode`
- introducing a tristate `{"off", "auto", "on"}` for two new fields of `PhotoCapabilities` and `PhotoSettings`: `Flash` and `Torch`,
- replacing `ExposureMode` with a data type similar to [FocusMode](https://w3c.github.io/mediacapture-image/#FocusMode), namely: ```enum { "unavailable", "manual", "single-shot", "continuous"};``` in both  `PhotoCapabilities` and `PhotoSettings`

WDYT?

**Comment by gmandyam** [comment]
@miguelao 

FillLightMode definition goes back to a group agreement from several years ago as to how to best reflect flash functionality.  It is still mentioned extensively in https://www.w3.org/TR/mediacapture-streams/#the-model-sources-sinks-constraints-and-settings.  I would be hesitant to change nomenclature on this setting without broader agreement within the Task Force to reflect this change throughout all of its specifications.   We can however move the RedEyeReduction flag to FillLightMode.

Regarding ExposureMode, I checked on the latest Snapdragon camera driver and the definition in the spec is still accurate.  My suggestion is to check with Safari implementation team as to whether the proposed change is really required before modifying the specification.

**Comment by miguelao** [comment]
Re. `FillLightMode`, Media Capture and Streams refers to it from a live capture POV, i.e. Torch mode. From an ImageCapture POV, there are more states present, namely the mentioned Torch on/off, and the new ones Flash off, on, or auto -- where Torch on overrides Flash mode.

Re. `ExposureMode`, Snapdragon presents exactly what I described as DSLR interface for e.g. handheld cameras, but the OS APIs follow a different path in both Android and Mac/iOS, so my proposal would be to follow the latter instead of the lower level APIs that would feel unintuitive for (Web)App developers. 

What do you mean with 
> the Safari Implementation team

? Has Safari implemented parts of this Spec? I would love to hear the feedback on these changes.

**Comment by gmandyam** [comment]
@miguelao 

>Snapdragon presents exactly what I described as DSLR interface for e.g. handheld cameras, but the OS APIs follow a different path in both Android and Mac/iOS ...

When we first started this work, some web runtime engines (e.g. FF OS) were directly integrating with the driver.  If we can safely state that web runtime engines are only integrating OS API's then I can see the logic behind the proposed change.

>Has Safari implemented parts of this Spec? I would love to hear the feedback on these changes.

Not as far as I know.  Once again, I was wondering if Safari would integrate with the OS API or with  the drivers directly on MAC/IoS devices.

**Comment by miguelao** [comment]
>  If we can safely state that web runtime engines are only integrating OS API's then I can see the logic behind the proposed change.

From Android and iOS point of view, this seems the current status. I wonder if we could rope someone from FF OS, @mounirlamouri, could you rope someone in?

**Comment by mounirlamouri** [comment]
@padenot would you know someone?

**Comment by miguelao** [comment]
I think that even if browsers were to decide to integrate lower level APIs (i.e. the chipsets one mentioned above), they'd have to bridge to gap to provide an exposure control API similar to the ternary manual/single-shot/continuous, since it's what web developers have become accustomed to.

I checked the USB Video Class and that doesn't provide the DSLR-like interface either: instead, it provides an intermediate level: manual, auto, aperture-priority and shutter-priority mode (Sec. `4.2.2.1.2 Auto-Exposure Mode Control` of `Universal Serial Bus Device Class Definition for Video Devices` Rev 1.5 Aug 9, 2012). USB VC is surfaced almost verbatim in Linux V4L2 API.

To complete the landscape, FF OS [CameraControl API](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/API/CameraControl) does not offer any changes to the Exposure mode, so I'm assuming it's always set to Auto; it provides exposure compensation (but that's a different concept not discussed in this issue).

**Comment by gmandyam** [comment]
Addressed in https://github.com/w3c/mediacapture-image/pull/51
