### ISSUE TITLE
Use consistent MediaDevices vs. navigator .getUserMedia, and the Promise-based API

### ISSUE THREAD

**Issue by dandv** [w3c/mediacapture-image#56]
The three [examples](https://www.w3.org/TR/image-capture/#examples) use a mix of the Promise-based gUM call, and use the [deprecated navigator.getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia).

Should they consistently use `MediaDevices.getUserMedia(...).then(...).catch(...)` ?

**Comment by gmandyam** [comment]
I think this is reasonable.  @miguelao - I assume Chrome will also deprecate navigator.gUM() ?

**Comment by miguelao** [comment]
Yeah, the Promise-based gUM() was launched in M53 (https://www.chromestatus.com/features/5755699816562688) -- however, navigator.gUM() is also still there :-)
In any case, I'd settle for all examples based on the Promise-gUM().

**Comment by gmandyam** [comment]
https://github.com/w3c/mediacapture-image/pull/57/commits/6dc6edd6ad7df1b270e936c3ddde74140a693a46 has been incorporated.  Thanks, @dandv.
