### ISSUE TITLE
Example 1 doesn't work

### ISSUE THREAD

**Issue by dandv** [w3c/mediacapture-image#62]
Even after fixing the syntax error after the second `then`, there is no `imageData` attribute in the `ImageBitmap` parameter of the promise returned by `grabFrame`.

**Comment by gmandyam** [comment]
Yes.  ImageBitmap does not allow direct retrieval of bitmap data (AFAICT).  What seems to work is to use canvas to draw the image with the ImageBitmap, and get the image data from the canvas element.  The example can be modified to reflect this approach.

**Comment by miguelao** [comment]
#114 should have addressed these concerns, ptal @dandv .

**Comment by miguelao** [comment]
Closing since the said example should work. @dandv, please reopen otherwise.
