### ISSUE TITLE
Document fails W3C validation

### ISSUE THREAD

**Issue by dandv** [w3c/mediacapture-image#64]
A bit ironic, but... https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fmediacapture-image%2Findex.html

**Comment by gmandyam** [comment]
Partially addressed by https://github.com/w3c/mediacapture-image/pull/65/commits/869a301215b28a307832cef128db0fb9f9ae52e1.  Will keep open for now.

**Comment by gmandyam** [comment]
Had to revert https://github.com/w3c/mediacapture-image/pull/65/commits/869a301215b28a307832cef128db0fb9f9ae52e1.  Declarative text does not display properly.

**Comment by dandv** [comment]
Happy to fix as soon as I understand what "declarative text" means.

**Comment by miguelao** [comment]
Only two Warnings remaining:
> Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

For both:
> `<section id='sotd'>`

and
> `<section id='abstract'>`

Which I think we can live with, so closing this issue perfunctorily.
