### ISSUE TITLE
WG CR review for mediacapture-image

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-image#69]
This issue serves to track internal WG review (in the WGs making up the mediacapture TF) of the mediacapture-image document for CR publication.
If you have reviewed the document, please add a “thumbs up” reaction to the issue.
If you find issues that you think need addressing before CR publication, please file the issue in Github and mention it in the comments.

The review lasts until Thursday, October 12, 2016. At that time, the chairs will decide whether or not the review result warrants asking the wider community to review the document for CR; if we do ask the wider community, a similar issue wil be filed for tracking that review.

**Comment by dandv** [comment]
For those of us not in the W3C:

WG = Working Group
TF = Task Force
CR = ?

**Comment by miguelao** [comment]
CR= Candidate Recommendation

https://www.w3.org/Consortium/Process/Process-19991111/tr.html

**Comment by alvestrand** [comment]
If you're not in the W3C and are not interested in how the W3C publishes its specifications, feel free to ignore this message.

**Comment by fluffy** [comment]
I think that a bunch of things need to be cleaned up before this is ready for CR. I entered a bunch of issues but most of them are fairly small and don't need many changes.

**Comment by stefhak** [comment]
I think this document is ready for the wide review that is part of the going to CR process.
