### ISSUE TITLE
Some PhotoCapabilities fields should return available options in addition to state

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-image#73]
Some fields of [`PhotoCapabilities`](https://w3c.github.io/mediacapture-image/index.html#PhotoCapabilities) do not represent capabilities, but configuration settings/current status. Those fields should be extended in some way to support sequences of options, e.g.: `whiteBalanceMode` could be a mix of a sequence of supported modes and a current status. Expressing this in some proto language, it should read back:

```
{ 
  supported : ["manual", "single-shot", "continuous" ];
  current: "manual";
}
```

**Comment by alvestrand** [comment]
This illustrates two things:
* PhotoCapabilities is misnamed. It should be called PhotoSettings.
* You are reinventing the getSettings / getCapabilities / getConstraints pattern of "constrainable". Are you sure you want to do that in a new syntax and semantic, rather than adopting "constrainable" again?

**Comment by miguelao** [comment]
@alvestrand, are you suggesting diving the current `PhotoCapabilities` into :
- a (new) `PhotoCapabitilies` without current-state information and
- a `PhotoSettings` with only the current settings, in such a way that it could be reapplied to `ImageCapture` via `setPhotoOptions()`
?

Also, could you please provide some links about the 'constrainability' you mention? :smile:

**Comment by alvestrand** [comment]
Constrainable pattern: https://w3c.github.io/mediacapture-main/getusermedia.html#constrainable-interface

Use of constrainable for MediaStreamTracks: https://w3c.github.io/mediacapture-main/getusermedia.html#tracks-and-constraints

**Comment by alvestrand** [comment]
What I'm suggesting is that you toss out all the current capabilities, and instead introduce:

- A list of constraints
- A getSettings() call that returns what the current settings are
- A getCapabilities() call that returns the range of possible values for each settings
- An applyConstraints() call to tell the UA the preferred values for the settings, and what ranges they are allowed to vary within.

The current options/settings/capabilities model has grown to almost equal complexity as the constraint model, without an underlying unified model to support them.

**Comment by fluffy** [comment]
I like what HTA is proposing here. It sounds complicated at first but it what we will need for extensibility in the future.

**Comment by beaufortfrancois** [comment]
@miguelao I like @alvestrand proposal. What do yo think?

**Comment by miguelao** [comment]
@alvestrand, @fluffy, @samdutton, @fluffy, @beaufortfrancois, @mounirlamouri, I have been reading (for the first time, I admit it) https://w3c.github.io/mediacapture-main/getusermedia.html#constrainable-interface and it should seem appropriate for the situation at hand.  It will need quite a bit of spec work and iterations on the current Chrome implementation, but is probably good in the long term. I will make a branch to iterate over the concrete wording of the changes, SG ?

**Comment by alvestrand** [comment]
Sounds good to me.
Please consult with @guidou to get pointers to pieces of Chromium code that can be reused for your usage.

Do we have any other browser vendors who have shown interest in implementing?

**Comment by gmandyam** [comment]
Sorry to come in late, but it seems that I have to address this issue once a year - why should 2016 be any different?

I gave my view on this topic last year in https://lists.w3.org/Archives/Public/public-media-capture/2015Mar/0038.html and https://lists.w3.org/Archives/Public/public-media-capture/2015Mar/0047.html. 

I still have not seen any convincing arguments in the discussion on this issue as to why constraints make sense for an API that should essentially be a straightforward mapping to either a camera driver (e.g. Snapdragon) or the Android Camera HAL.

The getSettings()/getCapabilities() methods are certainly something we can consider. but the benefits for adoption of the constraints mechanism are unclear to me.

**Comment by alvestrand** [comment]
It's no surprise - I did not agree with you the last time either, so we know that there is no WG consensus on the matter.

I've let it slide while there was no interest in implementation of the API; now that there is, it is probably good to resurface this issue in the WG.

**Comment by miguelao** [comment]
Just to give some context to the conversation and to make sure we're not splitting hairs, the effort needed to use this constrainable interface would be essentially a splitting of `getPhotoCapabilities` into 3 methods:
<table>
  <tr>
    <td rowspan="3" valign="top">Promise<PhotoCapabilities> getPhotoCapabilities(); </td>
    <td>Capabilities getCapabilities();</td>
  </tr>
  <tr>
    <td>Constraints getConstraints();</td>
  </tr>
  <tr>
    <td>Settings getSettings();</td>
  </tr>
  <tr>
    <td>Promise<void> setOptions(PhotoSettings? photoSettings);</td>
    <td>Promise<void> applyConstraints(optional Constraints constraints);</td>
  </tr>
</table>

`Constraints` ~= `PhotoSettings` and `Capabilities` ~= `PhotoCapabilities`. 

However, I'd like to also argue that the constrainable interface is not trivial to use: time and experience have taught us that, for the casual developer, `getUserMedia()s` constraints (e.g. sequences such as `{video:  { width: { exact: 640}, height: { min : 320}}}` ) are far from straightforward to compose and understand.  So, introducing this sophisticated idiom would be at the cost of mental friction and developers' brain time.

**Comment by miguelao** [comment]
@alvestrand @gmandyam what's the story here?

**Comment by gmandyam** [comment]
@miguelao 

I respect the view of @alvestrand, but I have not seen a convincing argument to adopt the constrainable interface and would argue against it at this point. 

I suggest addressing the original issue.  Getting back to the original issue - I believe MeteringMode can be redefined to achieve the desired result.

**Comment by miguelao** [comment]
Re. https://github.com/w3c/mediacapture-image/issues/73#issuecomment-257442334: IIUC, [`redEyeReduction`](https://w3c.github.io/mediacapture-image/#dom-photocapabilities-redeyereduction) could then be a [`MediaSettingsRange`](https://w3c.github.io/mediacapture-image/#idl-def-mediasettingsrange) with `min` == 0 (false), `max` == 1 (true, if supported), `step` = 1 and `current` = its state.

**Comment by miguelao** [comment]
With the current Constrainable Pattern, this is a non-issue, so closing.
