### ISSUE TITLE
types of setting objects

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-image#77]
Attributes such as exposureCompensation would be better as a double than a long x100. I can not see any disadvantage to using a double here.

**Comment by gmandyam** [comment]
@miguelao 

Any objection to the suggestion of @fluffy?

**Comment by miguelao** [comment]
@gmandyam, if you're ok I'm ok.
I'd suggest making it `float` which is generally as large as `int` (vs `double` which is usually larger) and I don't see any need for the extra ultra-precision.
I can write the PR then.

**Comment by miguelao** [comment]
#120 is the PR, @fluffy, @gmandyam, PTAL

**Comment by dontcallmedom** [comment]
@miguelao [`float` is discouraged](https://heycam.github.io/webidl/#idl-float):
> Unless there are specific reasons to use a 32 bit floating point type, specifications should use double rather than float, since the set of values that a double can represent more closely matches an ECMAScript Number.

**Comment by miguelao** [comment]
@dontcallmedom, that's exactly what I mentioned in https://github.com/w3c/mediacapture-image/pull/120#issue-187468145, but still "I feel that float can represent all of our value ranges and is smaller in size." Which one will win?

**Comment by dontcallmedom** [comment]
but it's not really smaller in size - the underlying ecmascript engine only sees double.

**Comment by miguelao** [comment]
Closed per #120.

**Comment by miguelao** [comment]
Landed in chrome, see https://crbug.com/663021.
