### ISSUE TITLE
Coordinate system 

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-image#78]
When using a point2d, is 0.5,0.5 the center? What is the top left (0,0) or ( 0, 1 )

Need to be clear on this

**Comment by miguelao** [comment]
Closing per #81. I took somewhat arbitrarily the origin of coordinates corresponding to the upper left corner of an image, with the x and y axis growing with column and row index, respectively. Please comment here if this surprises/confuses a new reader in your opinion.
