### ISSUE TITLE
Contrast, brightness, saturation and sharpness are undefined 

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-image#79]
These are not defined well enough to implement or for an application that wanted to use them to know how to set them.

**Comment by miguelao** [comment]
Added more literature on this, and a reference to the CIE International Lightning Vocabulary (I added a reference to it to the specref database).

**Comment by miguelao** [comment]
Closing per #81; however note (this is restating the note added to the text) that the specification of those settings/capabilities depends completely on the hardware implementation, which is essentially opaque, as you can see in the UVC specification (http://www.usb.org/developers/docs/devclass_docs/USB_Video_Class_1_5.zip).
