### ISSUE TITLE
Need to consider GPU copy

### ISSUE THREAD

**Issue by ds-hwang** [w3c/mediacapture-image#8]
Currently Mediastream Image Capture spec forces gpu based video to read back to system memory. It hits performance very badly.

First of all, FrameGrabEvent event inherently return software RGBA memory block. It should return handle to point out video frame.
```
interface FrameGrabEvent : Event {
    readonly    attribute ImageData imageData;
};
```

In following example, `canvas.getContext('2d').drawImage(imgData, ...)` is way inefficient than `canvas.getContext('2d').drawImage(videoElement, ...)`.
If video and canvas is gpu accelerated, `canvas.getContext('2d').drawImage(videoElement, ...)` can copy gpu texture to gpu texture. but `canvas.getContext('2d').drawImage(imgData, ...)` requires to read back gpu texture to cpu memory and then upload cpu memory to gpu texture.
```
   if (captureDevice) {
         frameVar = setInterval(captureDevice.grabFrame().then(processFrame()), 1000);
         }
     }

 function processFrame(e) {
     imgData = e.imageData;
     canvas.width = imgData.width;
     canvas.height = imgData.height;
     canvas.getContext('2d').drawImage(imgData, 0, 0,imgData.width,imgData.height);
     }
```

in the same sense, it's very inefficient to upload the captured frame to WebGL or WebCL.

**Comment by ds-hwang** [comment]
@huningxin ^

**Comment by gmandyam** [comment]
Will close this issue.  PR in https://github.com/w3c/mediacapture-image/pull/12 seems to solve. Changing from ImageData to ImageBitMap should address this problem.
