### ISSUE TITLE
Do the examples work ?

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-image#80]
For example, is captureDevice.photoCapabilities.redEyeReduction valid ?

**Comment by dandv** [comment]
I've made [Example 3 work](https://github.com/w3c/mediacapture-image/pull/66#issuecomment-249343302).

See also the [MediaStream ImageCapture polyfill](https://github.com/dandv/imagecapture).

**Comment by dandv** [comment]
This is obsoleted by #99, please close.

**Comment by gmandyam** [comment]
@fluffy 
OK if I close?  

I agree with @dandv.  https://github.com/w3c/mediacapture-image/issues/99 is the issue we are working towards resolving.

**Comment by fluffy** [comment]
Sounds good
