### ISSUE TITLE
DOMException (aka exception) should be used instead of ImageCaptureError

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/mediacapture-image#83]
See: https://www.w3.org/TR/WebIDL/#idl-exceptions

I don't think there is any need for the special `ImageCaptureError`

**Comment by beaufortfrancois** [comment]
gentle ping @miguelao

**Comment by miguelao** [comment]
Yeah, so, usage of `ImageCaptureError` says: 
> ...then the UA must return a promise rejected with a newly created ImageCaptureError with the appropriate errorDescription set.

 The uses of `ImageCaptureError` pertain to rejected Promises, not to exceptions thrown synchronously, so just to make sure: the proposal here is to change this mechanism to reject a Promise with a DOMException, correct?

**Comment by gmandyam** [comment]
@miguelao and @mounirlamouri 

ImageCaptureError allows for deriving the error string from a set of pre-defined values.  It was a spec convenience, versus having to define the DOMException name for every reason that the promise was rejected.  We can certainly move to DOMException, but I think we should define the returned exception in such a way to reflect the possible values of errorDescription.

**Comment by miguelao** [comment]
@gmandyam, @mounirlamouri, @beaufortfrancois please take a look at PR #93.

**Comment by miguelao** [comment]
@mounirlamouri , @beaufortfrancois please have a look at the code after #93, I'll preventively close this issue assuming your concerns are addressed, please reopen it otherwise.
