### ISSUE TITLE
previewStream is not specified

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/mediacapture-image#85]
It should be specified or removed from the specification.

**Comment by miguelao** [comment]
I'm in favour of removing it from the Spec altogether, @gmandyam, WDYT?

**Comment by gmandyam** [comment]
@miguelao 
Yes we can remove.  previewStream was intended to provide a directly renderable preview of any settings that are applied to the camera.  However, the preview can be created from the MediaStreamTrack used in the constructor.
