### ISSUE TITLE
Why does setOptions can't apply to the capture method?

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/mediacapture-image#86]
It's unclear to me why the options passed via `setOptions()` can't apply to `takePhoto()` and it needs another options bag. Is there a use case to have different set of options for I guess the preview and the actual capture?

**Comment by miguelao** [comment]
I'm not sure I understand the question: the same [`PhotoSettings`](https://w3c.github.io/mediacapture-image/#PhotoSettings) dictionary can be applied to both `setOptions()` and `takePhoto()` methods.

There is a small difference in intention, in that the settings applied via `setOptions()` are reflected (when applicable) immediately in the track associated to the capturer, whereas the ones applied to `takePhoto()` are used for the scoped of taking the picture only (sort of configure-capture-revert configuration to whatever it was before).  Does it make sense?

**Comment by mounirlamouri** [comment]
I do understand that `setOptions()` is for the preview and `takePhoto()` uses its own `PhotoSettings`. The question is "why" :) It's is very confusing and it seems that developers will simply keep a `var options` somewhere and pass it to both methods. What's the use case to have different options for previewing and capturing?

**Comment by miguelao** [comment]
I understand your point now. Are you proposing removing the optional `PhotoSettings` parameter from `takePhoto()`?

**Comment by miguelao** [comment]
@gmandyam, correct, I just wanted to make double sure we understand @mounirlamouri's concern.

**Comment by mounirlamouri** [comment]
Yes, I think that means reverting that change if there is no use case to
have the API looks like this.

**Comment by miguelao** [comment]
#90 closes this issue.

**Comment by dandv** [comment]
> What's the use case to have different options for previewing and capturing?

My understanding was that `grabFrame()` captured a frame from the previewStream using the current options, whatever they were, while takePhoto would set new options, then capture a frame (then presumably restore the original options).

In addition to this one-off use case, another use case is that grabFrame() would be much faster - changing certain options can take considerable time, especially setting autofocus.
