### ISSUE TITLE
Rename videoStreamTrack to track

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#87]
As we already pass a `track` MediaStreamTrack object into the constructor, it would be nicer to call it `track` as well and not `videoStreamTrack`.

``` diff
[Constructor(MediaStreamTrack track)]
interface ImageCapture {
-    readonly attribute MediaStreamTrack videoStreamTrack;
+    readonly attribute MediaStreamTrack track;
    readonly attribute MediaStream      previewStream;
    Promise<PhotoCapabilities> getPhotoCapabilities();
    Promise<void>              setOptions(PhotoSettings? photoSettings);
    Promise<Blob>              takePhoto(PhotoSettings? photoSettings);
    Promise<ImageBitmap>       grabFrame();
};
```

**Comment by miguelao** [comment]
SGTM but we depend on FF as well since they have implemented it (it's still
behind a flag); @gmandyam, wdyt?

**Comment by miguelao** [comment]
Concretely here: https://github.com/mozilla/gecko-dev/blob/master/dom/webidl/ImageCapture.webidl#L16 (implemented [here](https://github.com/mozilla/gecko-dev/blob/86897859913403b68829dbf9a154f5a87c4b0638/dom/media/imagecapture/ImageCapture.h#L88)) ;

@froydnj,  @alfredoyang, are you still active on this code? WDYT about the renaming suggestion?

**Comment by froydnj** [comment]
> @froydnj, are you still active on this code?

The only contributions I have to the implementation are refactoring changes.  I think @alfredoyang will have much more concrete suggestions than I would. :wink:

**Comment by dandv** [comment]
The spec states

> The MediaStreamTrack passed to the constructor must have its kind attribute set to "video"

That makes me think keeping the `videoStreamTrack` parameter name would be clearer than `track`.

**Comment by mounirlamouri** [comment]
Interesting, I would say exactly the opposite based on this :) In my opinion, because the `track` passed to the constructor _must_ be a video, there is no point in having to type again `video` in its name.

**Comment by dandv** [comment]
> there is no point in having to type again video in its name

But who would type this? The parameter name is descriptive; the developer can call `new ImageCapture(foo)`, and that would be correct. However, when an IDE offers autocomplete suggestions for `new ImageCapture(`, then `videoStreamTrack` would be more useful as a parameter name than `track`.

**Comment by mounirlamouri** [comment]
Hmm, I think we are not talking about the same thing :) François and I want the `readonly attribute` to change name, not the name of the constructor's argument (which btw is called `track`).

**Comment by dandv** [comment]
My bad, I was reading the [section on `takePhoto()`](https://w3c.github.io/mediacapture-image/#dom-imagecapture-takephoto):

> If the `readyState` of the `VideoStreamTrack` provided in the constructor is not "live" [...]

**Comment by miguelao** [comment]
@alfredoyang, it seems like the developers are rioting on the streets in support of this change, WDYT?  I don't have strong feelings either way but don't mind changing it now that it's all behind a flag.

**Comment by dandv** [comment]
So [the phrasing that confused me was changed](https://github.com/w3c/mediacapture-image/issues/91#issue-181946015). Color me neutral on this controversial change that allegedly has [yuge](http://knowyourmeme.com/memes/yuge) popular support.

**Comment by beaufortfrancois** [comment]
I can provide CLs for Firefox and Chromium if that helps moving forward with this change.

**Comment by miguelao** [comment]
@beaufortfrancois, if you can provide the FF CL that'd be great.  Do you see big chances of it being landed...? I'm just afraid we'd end up with diverging implementations.

**Comment by beaufortfrancois** [comment]
I can upload a CL and see what they think of it as I'll point to this issue.
WDYT?

**Comment by beaufortfrancois** [comment]
@alfredoyang I've uploaded [a patch](https://bugzilla.mozilla.org/page.cgi?id=splinter.html&bug=888177&attachment=8800544) you can see at  https://bugzilla.mozilla.org/show_bug.cgi?id=888177#c15
Please let me know how that looks for you.

**Comment by beaufortfrancois** [comment]
gentle ping @alfredoyang

**Comment by miguelao** [comment]
@jesup, @jan-ivar, does https://bugzilla.mozilla.org/show_bug.cgi?id=888177#c15 LGTY?

**Comment by jan-ivar** [comment]
@miguelao I'm all for the renaming. I'll put specific comments in the bug.

**Comment by beaufortfrancois** [comment]
@jan-ivar I'm not sure https://bugzilla.mozilla.org/show_bug.cgi?id=888177#c17 belongs to that CL. Shall we open a new one to address removing `VideoStreamTrack` entirely and use `MediaStreamTrack` instead?

**Comment by jan-ivar** [comment]
@beaufortfrancois This isn't a spec issue, so let's continue in the bug.

**Comment by miguelao** [comment]
Hey folks (@beaufortfrancois @jan-ivar @mounirlamouri) what's the situation here re. s/`videoStreamTrack`/`track`/ ?  I can whip a Cr CL in a jiffie, just let me know.

**Comment by jan-ivar** [comment]
The patch seems to have stalled, but I see no reason to wait to update the spec.

**Comment by beaufortfrancois** [comment]
Feel free to take ownership on https://bugzilla.mozilla.org/show_bug.cgi?id=888177#c17.
This still looks good to me!

**Comment by miguelao** [comment]
Spec-wise we're good, closing this issue.
