### ISSUE TITLE
Rename takePhoto method

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#88]
The Image Capture API is really about capturing images and I think the `takePhoto` method name could be improved and simply renamed to `capture`.

``` js
new ImageCapture(track).capture().then(blob => {
  document.querySelector('img').src = URL.createObjectURL(blob);
});
```

``` diff
[Constructor(MediaStreamTrack track)]
interface ImageCapture {
    readonly attribute MediaStreamTrack videoStreamTrack;
    readonly attribute MediaStream      previewStream;
    Promise<PhotoCapabilities> getPhotoCapabilities();
    Promise<void>              setOptions(PhotoSettings? photoSettings);
-    Promise<Blob>              takePhoto(PhotoSettings? photoSettings);
+    Promise<Blob>              capture(PhotoSettings? photoSettings);
    Promise<ImageBitmap>       grabFrame();
};
```

**Comment by beaufortfrancois** [comment]
What do you think @miguelao?

**Comment by gmandyam** [comment]
takephoto() and grabFrame() are both capture methods.  grabFrame() was introduced into the spec to allow for real-time processing on captured unencoded frames (see discussion in https://github.com/w3c/mediacapture-image/issues/72).   

Moreover, "capture" is generic and may result in confusion with the primary media capture interface (https://www.w3.org/TR/mediacapture-streams/).  Granted, the method would hang off of the ImageCapture interface, but I think it is not harmful to name methods as to their specific functionality to avoid any potential misinterpretation.  I am fine with changing the name of the method, but I am not convinced that capture() really "captures" the concept.

For historical reference, takePhoto() was a derivative of the original takePicture() proposal - see https://lists.w3.org/Archives/Public/public-media-capture/2012Aug/0032.html.

**Comment by dandv** [comment]
I imagine the average developer of a typical photo-enabled web app just wants to "take a photo", e.g. for the user's avatar. Most social apps would use this functionality. Thus, they'll search for a "browser take photo JS" library or code snippet, not for "capture".

**Comment by dandv** [comment]
Now that [takePhoto() no longer takes parameters](https://github.com/w3c/mediacapture-image/pull/90) and is [much closer to grabFrame()](https://github.com/w3c/mediacapture-image/issues/86#issuecomment-252811006), should we keep one or two capturing methods?

**Comment by beaufortfrancois** [comment]
Moving `grabFrame` outside of this API would be my favorite choice but I'm not sure we'll do that eventually.

**Comment by gmandyam** [comment]
@beaufortfrancois 

Re: grabFrame()

I proposed removal of this method at last year's TPAC:  see https://lists.w3.org/Archives/Public/public-media-capture/2015Nov/0024.html.

Mozilla in response requested that the method remain, but it return an ImageBitmap instead of an ImageData object (see https://github.com/w3c/mediacapture-image/pull/12).

I personally would prefer not to re-hash the subject, since it has already been discussed.

**Comment by mounirlamouri** [comment]
@gmandyam the pull request does not explain what was Mozilla's arguments and use cases. It would be great to understand what were the concern in order to decide if it's worth re-opening this topic.

**Comment by shwetank** [comment]
FWIW, I think takePhoto makes the intent sound a bit more clear (taking a photo. For photos, there is an inherent implication of being able to have the appropriate common settings like zoom, iso etc) whereas `capture` is not as clear. Taking a fast snapshot like what grabFrame was/is intended for is also technically 'capturing' an image). 

So for this one I would prefer to have it remain `takePhoto()`.

**Comment by beaufortfrancois** [comment]
How about other names then? Please vote by using 👍 reactions on comments below:

**Comment by beaufortfrancois** [comment]
- [ ] `captureImage` (my favorite)

**Comment by beaufortfrancois** [comment]
- [ ] `takePicture`

**Comment by dandv** [comment]
I voted for take(Photo|Picture) because I imagine the average developer of a typical photo-enabled web app just wants to "take a photo", e.g. for the user's avatar. Most social apps would use this functionality. Thus, they'll search for a "browser take photo JS" library or code snippet, not for "capture".

**Comment by mounirlamouri** [comment]
The Web has layers and we are making a low layer here enabling new capabilities. We shouldn't be targeting one specific use case. I think it's always good to look at other APIs and how they evolved and here we can see that the initial Camera API on Android had a [`takePicture` method](https://developer.android.com/reference/android/hardware/Camera.html#takePicture(android.hardware.Camera.ShutterCallback, android.hardware.Camera.PictureCallback, android.hardware.Camera.PictureCallback, android.hardware.Camera.PictureCallback)). The v2 of this API switched to a [`capture` method](https://developer.android.com/reference/android/hardware/camera2/CameraCaptureSession.html#capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession.CaptureCallback, android.os.Handler)). Android Camera API v2 is a more powerful API and probably closer to what this API should look like in the long run.

In general, I don't think the targeted audience of this API is the average developer. There are other ways in the platform to get an image without handling the capture. Most websites will likely use this, the same way most native applications delegate the image capture to the built-in camera app.

**Comment by shwetank** [comment]
thanks @mounirlamouri those are good points. Any particular reason why they changed it from `takePicture` to `capture` in v2? That would be interesting to know. 

AFAICT, the v2 of that API also has a support for camera capture sessions, which apparently v1 doesn't. If indeed we ever intend to support something in this api too, then indeed a name like `captureSession` would be better than something like `photoSession` and consequently `capture` or `captureImage` might be better than `takePhoto|Picture`. 

If we ever plan to have support for a camera capture sessions in the future version of this api (which I think might be a good idea), then I might have to switch my preference to `captureImage` otherwise I'm still for `capturePhoto`.

**Comment by shwetank** [comment]
Do we have a deadlock here? If so, then let me change my vote to `captureImage` to break it.

**Comment by miguelao** [comment]
This issue has been open for a while. Do we have a consensus, or should we leave the current name as is?

**Comment by beaufortfrancois** [comment]
My vote for `capture` and `captureImage` holds. I still think `takePicture` is bad to be honest.

**Comment by shwetank** [comment]
Based on more thinking along the lines of https://github.com/w3c/mediacapture-image/issues/88#issuecomment-255659925 I also vote for `capture` or `captureImage`.

**Comment by foolip** [comment]
There's an [Intent to Ship: Image Capture API](https://groups.google.com/a/chromium.org/d/msg/blink-dev/Y1hsOyT-vkk/n-8DDvKeCgAJ) for Blink, and whatever ships will then be the name we're stuck with. I have no opinions about the name, and we won't block shipping in Blink if there's no consensus here.

**Comment by mounirlamouri** [comment]
FWIW, I think renaming `takePhoto` to `capture` and even `grabFrame` to something like `preview` or `snapshot` might be nice. Also, as long as we do renames, renaming `PhotoSettings` to `ImageCaptureSettings` and `PhotoCapabilities` to `ImageCaptureCapabilities` would be nice :)

**Comment by miguelao** [comment]
This reminds me of [this quote](https://martinfowler.com/bliki/TwoHardThings.html):
>There are only two hard things in Computer Science: cache invalidation and naming things.

Let me try to summarize the current status (kind of complex, votes have changed sides):

dev  | `takePhoto()` | `capture()` | `captureImage()` | `takePicture()` |
-----|:--:|:--:|:--:|:--:|
@mounirlamouri  | nay | aye | ? | ? |
@beaufortfrancois | nay | aye | aye | nay |
@shwetank  | ? | ? | aye | ? |
@dandv | aye |  | | aye |
@miguelao | aye |  | | |

Again, we have no clear quorum, so I'd say no change, but we still have at least a week to present more arguments (any other votes, @gmandyam ?).

(Re. @mounirlamouri's other suggestions: `ImageCapture` API encompasses more than `Photo`-things, so I believe `PhotoSettings`/`PhotoCapabilities` are correct. For the renaming of `grabFrame()`, perhaps we could have another parallel issue?).

**Comment by beaufortfrancois** [comment]
Oops. I meant `takePhoto` is bad, not `takePicture`. I've edited my comment. 
Moreover @shwetank voted for `capture` AND `captureImage` in https://github.com/w3c/mediacapture-image/issues/88#issuecomment-290382125

I believe `capture` as 3 "aye" now ;)

Please update table @miguelao

**Comment by beaufortfrancois** [comment]
@miguelao Hopefully, we'll address this before this API ships in Chrome.

**Comment by miguelao** [comment]
Updated table (change in bold)

dev  | `takePhoto()` | `capture()` | `captureImage()` | `takePicture()` |
-----|:--:|:--:|:--:|:--:|
@mounirlamouri  | nay | aye | ? | ? |
@beaufortfrancois | nay | aye | aye | **aye** |
@shwetank  | ? | **aye** | aye | ? |
@dandv | aye |  | | aye |
@miguelao | aye |  | | |


Shipping wise: no sweat, it's literally a one line change in [`ImageCapture.idl`](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/imagecapture/ImageCapture.idl?q=imagecapture.idl&sq=package:chromium&dr), where it reads:
` [CallWith=ScriptState] Promise<Blob> takePhoto();`
it should read:
` [CallWith=ScriptState, ImplementedAs=takePhoto] Promise<Blob> capture();`

**Comment by shwetank** [comment]
Please mark my Nay for both `takePicture()` and `takePhoto()`. I don't have *that* much of a problem with the latter, but I think it's better now to go with the 'capture' route. I hope this makes thing clearer in the matrix.

**Comment by miguelao** [comment]
Second update (change in bold)

dev  | `takePhoto()` | `capture()` | `captureImage()` | `takePicture()` |
-----|:--:|:--:|:--:|:--:|
@mounirlamouri  | nay | aye | ? | ? |
@beaufortfrancois | nay | aye | aye | aye |
@shwetank  | **weak nay** | aye| aye | **nay** |
@dandv | aye |  | | aye |
@miguelao | aye |  | | |

**Comment by gmandyam** [comment]
Sorry for the late vote.  I am fine with takePhoto() - 'aye'.  I am also OK with captureImage() - 'aye'.  'nay' on capture(); as to why, suffice to say I generally agree with the sentiment behind https://github.com/w3c/webauthn/issues/329.  Indifferent on takePicture().

**Comment by miguelao** [comment]
With the latest vote we are back to the original situation.

dev  | `takePhoto()` | `capture()` | `captureImage()` | `takePicture()` |
-----|:--:|:--:|:--:|:--:|
@mounirlamouri  | nay | aye | ? | ? |
@beaufortfrancois | nay | aye | aye | aye |
@shwetank  | weak nay | aye| aye | nay |
@dandv | aye |  | | aye |
@miguelao | aye |  | | |
@gmandyam | **aye** | **nay**  |  **aye**| |

**Comment by yellowdoge** [comment]
Eventually Chrome has shipped with `takePhoto()` and no riots signalled this to be a particularly poor naming convention, so I'm tempted to close this issue. Please yell if this surprises you !
