### ISSUE TITLE
Make PhotoCapabilities object keys enumerable

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#97]
It would be nice if we could simply use `JSON.stringify` on the object returned by `getPhotoCapabilities`.

```js
imageCapture.getPhotoCapabilities().then(photoCapabilities => {
  console.log(JSON.stringify(photoCapabilities));
});
```

For now, it simply returns `{}`

**Comment by beaufortfrancois** [comment]
gentle ping @miguelao

**Comment by miguelao** [comment]
I agree with this idea, I wonder: Should this be done by means of an [`iterable`](https://heycam.github.io/webidl/#dfn-iterable-declaration) declaration in the `interface PhotoCapabilities`? Took a look around the Chromium code base and there are few examples of `<DOMString>` though.

**Comment by beaufortfrancois** [comment]
@jyasskin might help there.

**Comment by jyasskin** [comment]
Check out https://heycam.github.io/webidl/#idl-serializers for the way to define the `toJSON()` method.

**Comment by miguelao** [comment]
Thanks @jyasskin! Will work on a PR verys shortly, in the meantime https://crrev.com/2444433002 has the Chrome patch.

**Comment by miguelao** [comment]
@beaufortfrancois, during review of the [Chrome CL](https://codereview.chromium.org/2444433002/#msg7) @domenic raised an interesting concern about this extension, let me reproduce it here:
> In general serializers are used for data structures that the spec author
envisions being commonly transported and serialized via JSON. We don't add them
to anything that could conceivably be serialized, in general; we add them for
things that we plausibly expect authors to send over the wire.

Do we want the extra bloat, or are we OK with writing a JS snippet to generate a string from a  `PhotoCapabilities`?

**Comment by beaufortfrancois** [comment]
Concern is definitely valid.

For info, I found myself needing the `toJSON` binding when exploring the API and my intent was to show raw data from the API.

**Comment by domenic** [comment]
In general that's not a good reason to add toJSON methods. It's rather a reason to improve your browser's `console.log` to do so (as it does in e.g. Chrome).

**Comment by miguelao** [comment]
@beaufortfrancois , in light of the comments, do we still need a `serializer` ? Otherwise we could close this bug.

**Comment by beaufortfrancois** [comment]
Let's close this.
