### ISSUE TITLE
All examples are invalid

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#99]
### https://w3c.github.io/mediacapture-image/#grabbing-a-frame-for-post-processing

- extra parenthesis
- `if (captureDevice) {` is not necessary
- `imgData` is not defined
- `processFrame` can't use `imgData.data` as there as no `data` in `imageBitmap`.

### https://w3c.github.io/mediacapture-image/#taking-a-picture-with-red-eye-reduction-supported-and-used 

- `if (captureDevice) {` is not necessary
- `captureDevice.photoCapabilities.redEyeReduction` is invalid
- `redEyeReductionSetting` should be `redEyeReduction`
- `.then(captureDevice.takePhoto()` is missing a parenthesis
- `img.src = URL.createObjectURL(e.data);` should be `img.src = URL.createObjectURL(blob);`

### https://w3c.github.io/mediacapture-image/#repeated-grabbing-of-a-frame

- `var frameVar;` should be defined outside of this function and maybe even renamed 
- `if (captureDevice) {` is not necessary
- `then(processFrame())` should be `then(processFrame)`
- `function processFrame(e) {` should be `function processFrame(imgData) {`

**Comment by dandv** [comment]
#1 is a known issue - see #62.

**Comment by miguelao** [comment]
1. Doesn't make any sense, since `data` is not existing in `ImageBitmap` - we could just circulate the data through a `<canvas>` to get the same data, wdyt?
2. will be phased out by #103 (addressed in PR #111).
3. Addressed by #102

**Comment by miguelao** [comment]
#114 should have addressed these concerns, ptal @beaufortfrancois .

**Comment by beaufortfrancois** [comment]
It looks like some examples have not been tested at all. Here's a PR that should address this issue: https://github.com/w3c/mediacapture-image/pull/115

**Comment by miguelao** [comment]
I tried to synchronise all the examples back and forth between codepen.io
and the Spec, and #115 is only cosmetic changes IIUC (more consistent
variable naming, etc), but I might have missed something :smile:. 
What's the issue(s) with the current examples?

**Comment by beaufortfrancois** [comment]
You're right about cosmetic changes (consistent variable, `const` instead of `var`, `track` instead of `videoTrack` but there are more:

##### Update camera zoom and <code>takePhoto()</code>

- [ ] `document.querySelector('input[type="img"]');` is invalid. I've replaced it with `document.querySelector('img');`
- [ ] Since there was no `<video>` element, it didn't make sense to allow user to change zoom if he can't see changes. I've added one.
- [ ] In `takePhoto` function, imageCapture**r** variable was invalid. I've replaced it with `imageCapture`

##### Grabbing a Frame and Post-Processing

- [ ] `.then(processFrame(imgData))` has been simply replaced with  `.then(processFrame)`
